// GENERATED by spider-codegen — do not edit. Regenerate via scripts/generate-contract.sh.

enum Mode {
  airplane('AIRPLANE'),
  bicycle('BICYCLE'),
  bus('BUS'),
  cableCar('CABLE_CAR'),
  car('CAR'),
  carpool('CARPOOL'),
  coach('COACH'),
  ferry('FERRY'),
  flex('FLEX'),
  flexible('FLEXIBLE'),
  funicular('FUNICULAR'),
  gondola('GONDOLA'),
  legSwitch('LEG_SWITCH'),
  monorail('MONORAIL'),
  rail('RAIL'),
  scooter('SCOOTER'),
  subway('SUBWAY'),
  taxi('TAXI'),
  tram('TRAM'),
  transit('TRANSIT'),
  trolleybus('TROLLEYBUS'),
  walk('WALK'),
  unknown('UNKNOWN');

  const Mode(this.wire);

  final String wire;

  static Mode fromWire(String? value) {
    for (final e in Mode.values) {
      if (e.wire == value) return e;
    }
    return Mode.unknown;
  }

  String toJson() => wire;
}

class RealTimeEstimate {
  final String time;
  final String delay;

  const RealTimeEstimate({required this.time, required this.delay});

  factory RealTimeEstimate.fromJson(Map<String, dynamic> json) =>
      RealTimeEstimate(
        time: json['time'] as String,
        delay: json['delay'] as String,
      );

  Map<String, dynamic> toJson() => {'time': time, 'delay': delay};
}

class LegTime {
  final String scheduledTime;
  final RealTimeEstimate? estimated;

  const LegTime({required this.scheduledTime, this.estimated});

  factory LegTime.fromJson(Map<String, dynamic> json) => LegTime(
        scheduledTime: json['scheduledTime'] as String,
        estimated: json['estimated'] == null
            ? null
            : RealTimeEstimate.fromJson(
                json['estimated'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'scheduledTime': scheduledTime,
        if (estimated != null) 'estimated': estimated!.toJson(),
      };
}

enum RealtimeState {
  added('ADDED'),
  canceled('CANCELED'),
  modified('MODIFIED'),
  scheduled('SCHEDULED'),
  updated('UPDATED'),
  unknown('UNKNOWN');

  const RealtimeState(this.wire);

  final String wire;

  static RealtimeState fromWire(String? value) {
    for (final e in RealtimeState.values) {
      if (e.wire == value) return e;
    }
    return RealtimeState.unknown;
  }

  String toJson() => wire;
}

enum WheelchairBoarding {
  notPossible('NOT_POSSIBLE'),
  noInformation('NO_INFORMATION'),
  possible('POSSIBLE'),
  unknown('UNKNOWN');

  const WheelchairBoarding(this.wire);

  final String wire;

  static WheelchairBoarding fromWire(String? value) {
    for (final e in WheelchairBoarding.values) {
      if (e.wire == value) return e;
    }
    return WheelchairBoarding.unknown;
  }

  String toJson() => wire;
}

class Stop {
  final String gtfsId;
  final WheelchairBoarding? wheelchairBoarding;

  const Stop({required this.gtfsId, this.wheelchairBoarding});

  factory Stop.fromJson(Map<String, dynamic> json) => Stop(
        gtfsId: json['gtfsId'] as String,
        wheelchairBoarding: json['wheelchairBoarding'] == null
            ? null
            : WheelchairBoarding.fromWire(json['wheelchairBoarding'] as String),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        if (wheelchairBoarding != null)
          'wheelchairBoarding': wheelchairBoarding!.toJson(),
      };
}

class Place {
  final String? name;
  final Stop? stop;

  const Place({this.name, this.stop});

  factory Place.fromJson(Map<String, dynamic> json) => Place(
        name: json['name'] as String?,
        stop: json['stop'] == null
            ? null
            : Stop.fromJson(json['stop'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (name != null) 'name': name!,
        if (stop != null) 'stop': stop!.toJson(),
      };
}

class Route {
  final String? shortName;
  final String? longName;

  const Route({this.shortName, this.longName});

  factory Route.fromJson(Map<String, dynamic> json) => Route(
        shortName: json['shortName'] as String?,
        longName: json['longName'] as String?,
      );

  Map<String, dynamic> toJson() => {
        if (shortName != null) 'shortName': shortName!,
        if (longName != null) 'longName': longName!,
      };
}

enum BikesAllowed {
  allowed('ALLOWED'),
  notAllowed('NOT_ALLOWED'),
  noInformation('NO_INFORMATION'),
  unknown('UNKNOWN');

  const BikesAllowed(this.wire);

  final String wire;

  static BikesAllowed fromWire(String? value) {
    for (final e in BikesAllowed.values) {
      if (e.wire == value) return e;
    }
    return BikesAllowed.unknown;
  }

  String toJson() => wire;
}

class Trip {
  final String gtfsId;
  final BikesAllowed? bikesAllowed;

  const Trip({required this.gtfsId, this.bikesAllowed});

  factory Trip.fromJson(Map<String, dynamic> json) => Trip(
        gtfsId: json['gtfsId'] as String,
        bikesAllowed: json['bikesAllowed'] == null
            ? null
            : BikesAllowed.fromWire(json['bikesAllowed'] as String),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        if (bikesAllowed != null) 'bikesAllowed': bikesAllowed!.toJson(),
      };
}

class Geometry {
  final String? points;

  const Geometry({this.points});

  factory Geometry.fromJson(Map<String, dynamic> json) =>
      Geometry(points: json['points'] as String?);

  Map<String, dynamic> toJson() => {if (points != null) 'points': points!};
}

class Leg {
  final LegTime start;
  final LegTime end;
  final Place from;
  final Place to;
  final Mode? mode;
  final RealtimeState? realtimeState;
  final bool? realTime;
  final Route? route;
  final String? headsign;
  final double? distance;
  final double? duration;
  final double? accessibilityScore;
  final Trip? trip;
  final Geometry? legGeometry;

  const Leg({
    required this.start,
    required this.end,
    required this.from,
    required this.to,
    this.mode,
    this.realtimeState,
    this.realTime,
    this.route,
    this.headsign,
    this.distance,
    this.duration,
    this.accessibilityScore,
    this.trip,
    this.legGeometry,
  });

  factory Leg.fromJson(Map<String, dynamic> json) => Leg(
        start: LegTime.fromJson(json['start'] as Map<String, dynamic>),
        end: LegTime.fromJson(json['end'] as Map<String, dynamic>),
        from: Place.fromJson(json['from'] as Map<String, dynamic>),
        to: Place.fromJson(json['to'] as Map<String, dynamic>),
        mode:
            json['mode'] == null ? null : Mode.fromWire(json['mode'] as String),
        realtimeState: json['realtimeState'] == null
            ? null
            : RealtimeState.fromWire(json['realtimeState'] as String),
        realTime: json['realTime'] as bool?,
        route: json['route'] == null
            ? null
            : Route.fromJson(json['route'] as Map<String, dynamic>),
        headsign: json['headsign'] as String?,
        distance: (json['distance'] as num?)?.toDouble(),
        duration: (json['duration'] as num?)?.toDouble(),
        accessibilityScore: (json['accessibilityScore'] as num?)?.toDouble(),
        trip: json['trip'] == null
            ? null
            : Trip.fromJson(json['trip'] as Map<String, dynamic>),
        legGeometry: json['legGeometry'] == null
            ? null
            : Geometry.fromJson(json['legGeometry'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'start': start.toJson(),
        'end': end.toJson(),
        'from': from.toJson(),
        'to': to.toJson(),
        if (mode != null) 'mode': mode!.toJson(),
        if (realtimeState != null) 'realtimeState': realtimeState!.toJson(),
        if (realTime != null) 'realTime': realTime!,
        if (route != null) 'route': route!.toJson(),
        if (headsign != null) 'headsign': headsign!,
        if (distance != null) 'distance': distance!,
        if (duration != null) 'duration': duration!,
        if (accessibilityScore != null)
          'accessibilityScore': accessibilityScore!,
        if (trip != null) 'trip': trip!.toJson(),
        if (legGeometry != null) 'legGeometry': legGeometry!.toJson(),
      };
}

class Itinerary {
  final int numberOfTransfers;
  final List<Leg> legs;
  final String? start;
  final String? end;
  final int? duration;
  final int? waitingTime;
  final double? accessibilityScore;

  const Itinerary({
    required this.numberOfTransfers,
    required this.legs,
    this.start,
    this.end,
    this.duration,
    this.waitingTime,
    this.accessibilityScore,
  });

  factory Itinerary.fromJson(Map<String, dynamic> json) => Itinerary(
        numberOfTransfers: (json['numberOfTransfers'] as num).toInt(),
        legs: (json['legs'] as List<dynamic>)
            .map((e) => Leg.fromJson(e as Map<String, dynamic>))
            .toList(),
        start: json['start'] as String?,
        end: json['end'] as String?,
        duration: (json['duration'] as num?)?.toInt(),
        waitingTime: (json['waitingTime'] as num?)?.toInt(),
        accessibilityScore: (json['accessibilityScore'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'numberOfTransfers': numberOfTransfers,
        'legs': legs.map((e) => e.toJson()).toList(),
        if (start != null) 'start': start!,
        if (end != null) 'end': end!,
        if (duration != null) 'duration': duration!,
        if (waitingTime != null) 'waitingTime': waitingTime!,
        if (accessibilityScore != null)
          'accessibilityScore': accessibilityScore!,
      };
}

class PlanEdge {
  final String cursor;
  final Itinerary node;

  const PlanEdge({required this.cursor, required this.node});

  factory PlanEdge.fromJson(Map<String, dynamic> json) => PlanEdge(
        cursor: json['cursor'] as String,
        node: Itinerary.fromJson(json['node'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {'cursor': cursor, 'node': node.toJson()};
}

class PlanPageInfo {
  final bool hasNextPage;
  final bool hasPreviousPage;
  final String? startCursor;
  final String? endCursor;
  final String? searchWindowUsed;

  const PlanPageInfo({
    required this.hasNextPage,
    required this.hasPreviousPage,
    this.startCursor,
    this.endCursor,
    this.searchWindowUsed,
  });

  factory PlanPageInfo.fromJson(Map<String, dynamic> json) => PlanPageInfo(
        hasNextPage: json['hasNextPage'] as bool,
        hasPreviousPage: json['hasPreviousPage'] as bool,
        startCursor: json['startCursor'] as String?,
        endCursor: json['endCursor'] as String?,
        searchWindowUsed: json['searchWindowUsed'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'hasNextPage': hasNextPage,
        'hasPreviousPage': hasPreviousPage,
        if (startCursor != null) 'startCursor': startCursor!,
        if (endCursor != null) 'endCursor': endCursor!,
        if (searchWindowUsed != null) 'searchWindowUsed': searchWindowUsed!,
      };
}

enum RoutingErrorCode {
  locationNotFound('LOCATION_NOT_FOUND'),
  noStopsInRange('NO_STOPS_IN_RANGE'),
  noTransitConnection('NO_TRANSIT_CONNECTION'),
  noTransitConnectionInSearchWindow('NO_TRANSIT_CONNECTION_IN_SEARCH_WINDOW'),
  outsideBounds('OUTSIDE_BOUNDS'),
  outsideServicePeriod('OUTSIDE_SERVICE_PERIOD'),
  walkingBetterThanTransit('WALKING_BETTER_THAN_TRANSIT'),
  unknown('UNKNOWN');

  const RoutingErrorCode(this.wire);

  final String wire;

  static RoutingErrorCode fromWire(String? value) {
    for (final e in RoutingErrorCode.values) {
      if (e.wire == value) return e;
    }
    return RoutingErrorCode.unknown;
  }

  String toJson() => wire;
}

enum InputField {
  dateTime('DATE_TIME'),
  from('FROM'),
  to('TO'),
  via('VIA'),
  unknown('UNKNOWN');

  const InputField(this.wire);

  final String wire;

  static InputField fromWire(String? value) {
    for (final e in InputField.values) {
      if (e.wire == value) return e;
    }
    return InputField.unknown;
  }

  String toJson() => wire;
}

class RoutingError {
  final RoutingErrorCode code;
  final String description;
  final InputField? inputField;

  const RoutingError({
    required this.code,
    required this.description,
    this.inputField,
  });

  factory RoutingError.fromJson(Map<String, dynamic> json) => RoutingError(
        code: RoutingErrorCode.fromWire(json['code'] as String),
        description: json['description'] as String,
        inputField: json['inputField'] == null
            ? null
            : InputField.fromWire(json['inputField'] as String),
      );

  Map<String, dynamic> toJson() => {
        'code': code.toJson(),
        'description': description,
        if (inputField != null) 'inputField': inputField!.toJson(),
      };
}

class PlanConnection {
  final PlanPageInfo pageInfo;
  final List<RoutingError> routingErrors;
  final List<PlanEdge>? edges;
  final String? searchDateTime;

  const PlanConnection({
    required this.pageInfo,
    required this.routingErrors,
    this.edges,
    this.searchDateTime,
  });

  factory PlanConnection.fromJson(Map<String, dynamic> json) => PlanConnection(
        pageInfo:
            PlanPageInfo.fromJson(json['pageInfo'] as Map<String, dynamic>),
        routingErrors: (json['routingErrors'] as List<dynamic>)
            .map((e) => RoutingError.fromJson(e as Map<String, dynamic>))
            .toList(),
        edges: (json['edges'] as List<dynamic>?)
            ?.map((e) => PlanEdge.fromJson(e as Map<String, dynamic>))
            .toList(),
        searchDateTime: json['searchDateTime'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'pageInfo': pageInfo.toJson(),
        'routingErrors': routingErrors.map((e) => e.toJson()).toList(),
        if (edges != null) 'edges': edges!.map((e) => e.toJson()).toList(),
        if (searchDateTime != null) 'searchDateTime': searchDateTime!,
      };
}

class PlanConnectionData {
  final PlanConnection? planConnection;

  const PlanConnectionData({this.planConnection});

  factory PlanConnectionData.fromJson(Map<String, dynamic> json) =>
      PlanConnectionData(
        planConnection: json['planConnection'] == null
            ? null
            : PlanConnection.fromJson(
                json['planConnection'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (planConnection != null) 'planConnection': planConnection!.toJson(),
      };
}

class GraphQLError {
  final String message;
  final List<String>? path;

  const GraphQLError({required this.message, this.path});

  factory GraphQLError.fromJson(Map<String, dynamic> json) => GraphQLError(
        message: json['message'] as String,
        path:
            (json['path'] as List<dynamic>?)?.map((e) => e as String).toList(),
      );

  Map<String, dynamic> toJson() => {
        'message': message,
        if (path != null) 'path': path!.map((e) => e).toList(),
      };
}

class PlanConnectionResponse {
  final PlanConnectionData? data;
  final List<GraphQLError>? errors;

  const PlanConnectionResponse({this.data, this.errors});

  factory PlanConnectionResponse.fromJson(Map<String, dynamic> json) =>
      PlanConnectionResponse(
        data: json['data'] == null
            ? null
            : PlanConnectionData.fromJson(json['data'] as Map<String, dynamic>),
        errors: (json['errors'] as List<dynamic>?)
            ?.map((e) => GraphQLError.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (data != null) 'data': data!.toJson(),
        if (errors != null) 'errors': errors!.map((e) => e.toJson()).toList(),
      };
}

class PlanDateTimeInput {
  final String? earliestDeparture;
  final String? latestArrival;

  const PlanDateTimeInput({this.earliestDeparture, this.latestArrival});

  factory PlanDateTimeInput.fromJson(Map<String, dynamic> json) =>
      PlanDateTimeInput(
        earliestDeparture: json['earliestDeparture'] as String?,
        latestArrival: json['latestArrival'] as String?,
      );

  Map<String, dynamic> toJson() => {
        if (earliestDeparture != null) 'earliestDeparture': earliestDeparture!,
        if (latestArrival != null) 'latestArrival': latestArrival!,
      };
}

class PlanLabeledLocationInput {
  final PlanLocationInput location;
  final String? label;

  const PlanLabeledLocationInput({required this.location, this.label});

  factory PlanLabeledLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanLabeledLocationInput(
        location: PlanLocationInput.fromJson(
          json['location'] as Map<String, dynamic>,
        ),
        label: json['label'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'location': location.toJson(),
        if (label != null) 'label': label!,
      };
}

class PlanLocationInput {
  final PlanCoordinateInput? coordinate;
  final PlanStopLocationInput? stopLocation;

  const PlanLocationInput({this.coordinate, this.stopLocation});

  factory PlanLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanLocationInput(
        coordinate: json['coordinate'] == null
            ? null
            : PlanCoordinateInput.fromJson(
                json['coordinate'] as Map<String, dynamic>,
              ),
        stopLocation: json['stopLocation'] == null
            ? null
            : PlanStopLocationInput.fromJson(
                json['stopLocation'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (coordinate != null) 'coordinate': coordinate!.toJson(),
        if (stopLocation != null) 'stopLocation': stopLocation!.toJson(),
      };
}

class PlanCoordinateInput {
  final double latitude;
  final double longitude;

  const PlanCoordinateInput({required this.latitude, required this.longitude});

  factory PlanCoordinateInput.fromJson(Map<String, dynamic> json) =>
      PlanCoordinateInput(
        latitude: (json['latitude'] as num).toDouble(),
        longitude: (json['longitude'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'latitude': latitude,
        'longitude': longitude,
      };
}

class PlanStopLocationInput {
  final String stopLocationId;

  const PlanStopLocationInput({required this.stopLocationId});

  factory PlanStopLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanStopLocationInput(stopLocationId: json['stopLocationId'] as String);

  Map<String, dynamic> toJson() => {'stopLocationId': stopLocationId};
}

class PlanViaLocationInput {
  final PlanPassThroughViaLocationInput? passThrough;
  final PlanVisitViaLocationInput? visit;

  const PlanViaLocationInput({this.passThrough, this.visit});

  factory PlanViaLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanViaLocationInput(
        passThrough: json['passThrough'] == null
            ? null
            : PlanPassThroughViaLocationInput.fromJson(
                json['passThrough'] as Map<String, dynamic>,
              ),
        visit: json['visit'] == null
            ? null
            : PlanVisitViaLocationInput.fromJson(
                json['visit'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (passThrough != null) 'passThrough': passThrough!.toJson(),
        if (visit != null) 'visit': visit!.toJson(),
      };
}

class PlanPassThroughViaLocationInput {
  final List<String> stopLocationIds;
  final String? label;

  const PlanPassThroughViaLocationInput({
    required this.stopLocationIds,
    this.label,
  });

  factory PlanPassThroughViaLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanPassThroughViaLocationInput(
        stopLocationIds: (json['stopLocationIds'] as List<dynamic>)
            .map((e) => e as String)
            .toList(),
        label: json['label'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'stopLocationIds': stopLocationIds.map((e) => e).toList(),
        if (label != null) 'label': label!,
      };
}

class PlanVisitViaLocationInput {
  final PlanCoordinateInput? coordinate;
  final String? label;
  final String? minimumWaitTime;
  final List<String>? stopLocationIds;

  const PlanVisitViaLocationInput({
    this.coordinate,
    this.label,
    this.minimumWaitTime,
    this.stopLocationIds,
  });

  factory PlanVisitViaLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanVisitViaLocationInput(
        coordinate: json['coordinate'] == null
            ? null
            : PlanCoordinateInput.fromJson(
                json['coordinate'] as Map<String, dynamic>,
              ),
        label: json['label'] as String?,
        minimumWaitTime: json['minimumWaitTime'] as String?,
        stopLocationIds: (json['stopLocationIds'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (coordinate != null) 'coordinate': coordinate!.toJson(),
        if (label != null) 'label': label!,
        if (minimumWaitTime != null) 'minimumWaitTime': minimumWaitTime!,
        if (stopLocationIds != null)
          'stopLocationIds': stopLocationIds!.map((e) => e).toList(),
      };
}

class PlanModesInput {
  final List<PlanDirectMode>? direct;
  final bool? directOnly;
  final PlanTransitModesInput? transit;
  final bool? transitOnly;

  const PlanModesInput({
    this.direct,
    this.directOnly,
    this.transit,
    this.transitOnly,
  });

  factory PlanModesInput.fromJson(Map<String, dynamic> json) => PlanModesInput(
        direct: (json['direct'] as List<dynamic>?)
            ?.map((e) => PlanDirectMode.fromWire(e as String))
            .toList(),
        directOnly: json['directOnly'] as bool?,
        transit: json['transit'] == null
            ? null
            : PlanTransitModesInput.fromJson(
                json['transit'] as Map<String, dynamic>,
              ),
        transitOnly: json['transitOnly'] as bool?,
      );

  Map<String, dynamic> toJson() => {
        if (direct != null) 'direct': direct!.map((e) => e.toJson()).toList(),
        if (directOnly != null) 'directOnly': directOnly!,
        if (transit != null) 'transit': transit!.toJson(),
        if (transitOnly != null) 'transitOnly': transitOnly!,
      };
}

enum PlanDirectMode {
  bicycle('BICYCLE'),
  bicycleParking('BICYCLE_PARKING'),
  bicycleRental('BICYCLE_RENTAL'),
  car('CAR'),
  carParking('CAR_PARKING'),
  carRental('CAR_RENTAL'),
  flex('FLEX'),
  scooterRental('SCOOTER_RENTAL'),
  walk('WALK'),
  unknown('UNKNOWN');

  const PlanDirectMode(this.wire);

  final String wire;

  static PlanDirectMode fromWire(String? value) {
    for (final e in PlanDirectMode.values) {
      if (e.wire == value) return e;
    }
    return PlanDirectMode.unknown;
  }

  String toJson() => wire;
}

class PlanTransitModesInput {
  final List<PlanAccessMode>? access;
  final List<PlanEgressMode>? egress;
  final List<PlanTransferMode>? transfer;
  final List<PlanTransitModePreferenceInput>? transit;

  const PlanTransitModesInput({
    this.access,
    this.egress,
    this.transfer,
    this.transit,
  });

  factory PlanTransitModesInput.fromJson(Map<String, dynamic> json) =>
      PlanTransitModesInput(
        access: (json['access'] as List<dynamic>?)
            ?.map((e) => PlanAccessMode.fromWire(e as String))
            .toList(),
        egress: (json['egress'] as List<dynamic>?)
            ?.map((e) => PlanEgressMode.fromWire(e as String))
            .toList(),
        transfer: (json['transfer'] as List<dynamic>?)
            ?.map((e) => PlanTransferMode.fromWire(e as String))
            .toList(),
        transit: (json['transit'] as List<dynamic>?)
            ?.map(
              (e) => PlanTransitModePreferenceInput.fromJson(
                e as Map<String, dynamic>,
              ),
            )
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (access != null) 'access': access!.map((e) => e.toJson()).toList(),
        if (egress != null) 'egress': egress!.map((e) => e.toJson()).toList(),
        if (transfer != null)
          'transfer': transfer!.map((e) => e.toJson()).toList(),
        if (transit != null)
          'transit': transit!.map((e) => e.toJson()).toList(),
      };
}

enum PlanAccessMode {
  bicycle('BICYCLE'),
  bicycleParking('BICYCLE_PARKING'),
  bicycleRental('BICYCLE_RENTAL'),
  car('CAR'),
  carDropOff('CAR_DROP_OFF'),
  carParking('CAR_PARKING'),
  carRental('CAR_RENTAL'),
  flex('FLEX'),
  scooterRental('SCOOTER_RENTAL'),
  walk('WALK'),
  unknown('UNKNOWN');

  const PlanAccessMode(this.wire);

  final String wire;

  static PlanAccessMode fromWire(String? value) {
    for (final e in PlanAccessMode.values) {
      if (e.wire == value) return e;
    }
    return PlanAccessMode.unknown;
  }

  String toJson() => wire;
}

enum PlanEgressMode {
  bicycle('BICYCLE'),
  bicycleRental('BICYCLE_RENTAL'),
  car('CAR'),
  carPickup('CAR_PICKUP'),
  carRental('CAR_RENTAL'),
  flex('FLEX'),
  scooterRental('SCOOTER_RENTAL'),
  walk('WALK'),
  unknown('UNKNOWN');

  const PlanEgressMode(this.wire);

  final String wire;

  static PlanEgressMode fromWire(String? value) {
    for (final e in PlanEgressMode.values) {
      if (e.wire == value) return e;
    }
    return PlanEgressMode.unknown;
  }

  String toJson() => wire;
}

enum PlanTransferMode {
  bicycle('BICYCLE'),
  car('CAR'),
  walk('WALK'),
  unknown('UNKNOWN');

  const PlanTransferMode(this.wire);

  final String wire;

  static PlanTransferMode fromWire(String? value) {
    for (final e in PlanTransferMode.values) {
      if (e.wire == value) return e;
    }
    return PlanTransferMode.unknown;
  }

  String toJson() => wire;
}

class PlanTransitModePreferenceInput {
  final TransitMode mode;
  final TransitModePreferenceCostInput? cost;

  const PlanTransitModePreferenceInput({required this.mode, this.cost});

  factory PlanTransitModePreferenceInput.fromJson(Map<String, dynamic> json) =>
      PlanTransitModePreferenceInput(
        mode: TransitMode.fromWire(json['mode'] as String),
        cost: json['cost'] == null
            ? null
            : TransitModePreferenceCostInput.fromJson(
                json['cost'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        'mode': mode.toJson(),
        if (cost != null) 'cost': cost!.toJson(),
      };
}

class TransitModePreferenceCostInput {
  final double reluctance;

  const TransitModePreferenceCostInput({required this.reluctance});

  factory TransitModePreferenceCostInput.fromJson(Map<String, dynamic> json) =>
      TransitModePreferenceCostInput(
        reluctance: (json['reluctance'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {'reluctance': reluctance};
}

enum TransitMode {
  airplane('AIRPLANE'),
  bus('BUS'),
  cableCar('CABLE_CAR'),
  carpool('CARPOOL'),
  coach('COACH'),
  ferry('FERRY'),
  funicular('FUNICULAR'),
  gondola('GONDOLA'),
  monorail('MONORAIL'),
  rail('RAIL'),
  snowAndIce('SNOW_AND_ICE'),
  subway('SUBWAY'),
  taxi('TAXI'),
  tram('TRAM'),
  trolleybus('TROLLEYBUS'),
  unknown('UNKNOWN');

  const TransitMode(this.wire);

  final String wire;

  static TransitMode fromWire(String? value) {
    for (final e in TransitMode.values) {
      if (e.wire == value) return e;
    }
    return TransitMode.unknown;
  }

  String toJson() => wire;
}

class PlanPreferencesInput {
  final AccessibilityPreferencesInput? accessibility;
  final PlanStreetPreferencesInput? street;
  final TransitPreferencesInput? transit;

  const PlanPreferencesInput({this.accessibility, this.street, this.transit});

  factory PlanPreferencesInput.fromJson(Map<String, dynamic> json) =>
      PlanPreferencesInput(
        accessibility: json['accessibility'] == null
            ? null
            : AccessibilityPreferencesInput.fromJson(
                json['accessibility'] as Map<String, dynamic>,
              ),
        street: json['street'] == null
            ? null
            : PlanStreetPreferencesInput.fromJson(
                json['street'] as Map<String, dynamic>,
              ),
        transit: json['transit'] == null
            ? null
            : TransitPreferencesInput.fromJson(
                json['transit'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (accessibility != null) 'accessibility': accessibility!.toJson(),
        if (street != null) 'street': street!.toJson(),
        if (transit != null) 'transit': transit!.toJson(),
      };
}

class AccessibilityPreferencesInput {
  final WheelchairPreferencesInput? wheelchair;

  const AccessibilityPreferencesInput({this.wheelchair});

  factory AccessibilityPreferencesInput.fromJson(Map<String, dynamic> json) =>
      AccessibilityPreferencesInput(
        wheelchair: json['wheelchair'] == null
            ? null
            : WheelchairPreferencesInput.fromJson(
                json['wheelchair'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (wheelchair != null) 'wheelchair': wheelchair!.toJson(),
      };
}

class WheelchairPreferencesInput {
  final bool? enabled;

  const WheelchairPreferencesInput({this.enabled});

  factory WheelchairPreferencesInput.fromJson(Map<String, dynamic> json) =>
      WheelchairPreferencesInput(enabled: json['enabled'] as bool?);

  Map<String, dynamic> toJson() => {if (enabled != null) 'enabled': enabled!};
}

class PlanStreetPreferencesInput {
  final BicyclePreferencesInput? bicycle;
  final CarPreferencesInput? car;
  final ScooterPreferencesInput? scooter;
  final WalkPreferencesInput? walk;

  const PlanStreetPreferencesInput({
    this.bicycle,
    this.car,
    this.scooter,
    this.walk,
  });

  factory PlanStreetPreferencesInput.fromJson(Map<String, dynamic> json) =>
      PlanStreetPreferencesInput(
        bicycle: json['bicycle'] == null
            ? null
            : BicyclePreferencesInput.fromJson(
                json['bicycle'] as Map<String, dynamic>,
              ),
        car: json['car'] == null
            ? null
            : CarPreferencesInput.fromJson(json['car'] as Map<String, dynamic>),
        scooter: json['scooter'] == null
            ? null
            : ScooterPreferencesInput.fromJson(
                json['scooter'] as Map<String, dynamic>,
              ),
        walk: json['walk'] == null
            ? null
            : WalkPreferencesInput.fromJson(
                json['walk'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (bicycle != null) 'bicycle': bicycle!.toJson(),
        if (car != null) 'car': car!.toJson(),
        if (scooter != null) 'scooter': scooter!.toJson(),
        if (walk != null) 'walk': walk!.toJson(),
      };
}

class BicyclePreferencesInput {
  final int? boardCost;
  final CyclingOptimizationInput? optimization;
  final BicycleParkingPreferencesInput? parking;
  final double? reluctance;
  final BicycleRentalPreferencesInput? rental;
  final double? speed;
  final BicycleWalkPreferencesInput? walk;

  const BicyclePreferencesInput({
    this.boardCost,
    this.optimization,
    this.parking,
    this.reluctance,
    this.rental,
    this.speed,
    this.walk,
  });

  factory BicyclePreferencesInput.fromJson(Map<String, dynamic> json) =>
      BicyclePreferencesInput(
        boardCost: (json['boardCost'] as num?)?.toInt(),
        optimization: json['optimization'] == null
            ? null
            : CyclingOptimizationInput.fromJson(
                json['optimization'] as Map<String, dynamic>,
              ),
        parking: json['parking'] == null
            ? null
            : BicycleParkingPreferencesInput.fromJson(
                json['parking'] as Map<String, dynamic>,
              ),
        reluctance: (json['reluctance'] as num?)?.toDouble(),
        rental: json['rental'] == null
            ? null
            : BicycleRentalPreferencesInput.fromJson(
                json['rental'] as Map<String, dynamic>,
              ),
        speed: (json['speed'] as num?)?.toDouble(),
        walk: json['walk'] == null
            ? null
            : BicycleWalkPreferencesInput.fromJson(
                json['walk'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (boardCost != null) 'boardCost': boardCost!,
        if (optimization != null) 'optimization': optimization!.toJson(),
        if (parking != null) 'parking': parking!.toJson(),
        if (reluctance != null) 'reluctance': reluctance!,
        if (rental != null) 'rental': rental!.toJson(),
        if (speed != null) 'speed': speed!,
        if (walk != null) 'walk': walk!.toJson(),
      };
}

class CyclingOptimizationInput {
  final TriangleCyclingFactorsInput? triangle;
  final CyclingOptimizationType? type;

  const CyclingOptimizationInput({this.triangle, this.type});

  factory CyclingOptimizationInput.fromJson(Map<String, dynamic> json) =>
      CyclingOptimizationInput(
        triangle: json['triangle'] == null
            ? null
            : TriangleCyclingFactorsInput.fromJson(
                json['triangle'] as Map<String, dynamic>,
              ),
        type: json['type'] == null
            ? null
            : CyclingOptimizationType.fromWire(json['type'] as String),
      );

  Map<String, dynamic> toJson() => {
        if (triangle != null) 'triangle': triangle!.toJson(),
        if (type != null) 'type': type!.toJson(),
      };
}

class TriangleCyclingFactorsInput {
  final double flatness;
  final double safety;
  final double time;

  const TriangleCyclingFactorsInput({
    required this.flatness,
    required this.safety,
    required this.time,
  });

  factory TriangleCyclingFactorsInput.fromJson(Map<String, dynamic> json) =>
      TriangleCyclingFactorsInput(
        flatness: (json['flatness'] as num).toDouble(),
        safety: (json['safety'] as num).toDouble(),
        time: (json['time'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'flatness': flatness,
        'safety': safety,
        'time': time,
      };
}

enum CyclingOptimizationType {
  flatStreets('FLAT_STREETS'),
  safestStreets('SAFEST_STREETS'),
  safeStreets('SAFE_STREETS'),
  shortestDuration('SHORTEST_DURATION'),
  unknown('UNKNOWN');

  const CyclingOptimizationType(this.wire);

  final String wire;

  static CyclingOptimizationType fromWire(String? value) {
    for (final e in CyclingOptimizationType.values) {
      if (e.wire == value) return e;
    }
    return CyclingOptimizationType.unknown;
  }

  String toJson() => wire;
}

class BicycleParkingPreferencesInput {
  final List<ParkingFilter>? filters;
  final List<ParkingFilter>? preferred;
  final int? unpreferredCost;

  const BicycleParkingPreferencesInput({
    this.filters,
    this.preferred,
    this.unpreferredCost,
  });

  factory BicycleParkingPreferencesInput.fromJson(Map<String, dynamic> json) =>
      BicycleParkingPreferencesInput(
        filters: (json['filters'] as List<dynamic>?)
            ?.map((e) => ParkingFilter.fromJson(e as Map<String, dynamic>))
            .toList(),
        preferred: (json['preferred'] as List<dynamic>?)
            ?.map((e) => ParkingFilter.fromJson(e as Map<String, dynamic>))
            .toList(),
        unpreferredCost: (json['unpreferredCost'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        if (filters != null)
          'filters': filters!.map((e) => e.toJson()).toList(),
        if (preferred != null)
          'preferred': preferred!.map((e) => e.toJson()).toList(),
        if (unpreferredCost != null) 'unpreferredCost': unpreferredCost!,
      };
}

class ParkingFilter {
  final List<ParkingFilterOperation>? not;
  final List<ParkingFilterOperation>? select;

  const ParkingFilter({this.not, this.select});

  factory ParkingFilter.fromJson(Map<String, dynamic> json) => ParkingFilter(
        not: (json['not'] as List<dynamic>?)
            ?.map((e) =>
                ParkingFilterOperation.fromJson(e as Map<String, dynamic>))
            .toList(),
        select: (json['select'] as List<dynamic>?)
            ?.map((e) =>
                ParkingFilterOperation.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (not != null) 'not': not!.map((e) => e.toJson()).toList(),
        if (select != null) 'select': select!.map((e) => e.toJson()).toList(),
      };
}

class ParkingFilterOperation {
  final List<String>? tags;

  const ParkingFilterOperation({this.tags});

  factory ParkingFilterOperation.fromJson(Map<String, dynamic> json) =>
      ParkingFilterOperation(
        tags:
            (json['tags'] as List<dynamic>?)?.map((e) => e as String).toList(),
      );

  Map<String, dynamic> toJson() => {
        if (tags != null) 'tags': tags!.map((e) => e).toList(),
      };
}

class BicycleRentalPreferencesInput {
  final List<String>? allowedNetworks;
  final List<String>? bannedNetworks;
  final DestinationBicyclePolicyInput? destinationBicyclePolicy;

  const BicycleRentalPreferencesInput({
    this.allowedNetworks,
    this.bannedNetworks,
    this.destinationBicyclePolicy,
  });

  factory BicycleRentalPreferencesInput.fromJson(Map<String, dynamic> json) =>
      BicycleRentalPreferencesInput(
        allowedNetworks: (json['allowedNetworks'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
        bannedNetworks: (json['bannedNetworks'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
        destinationBicyclePolicy: json['destinationBicyclePolicy'] == null
            ? null
            : DestinationBicyclePolicyInput.fromJson(
                json['destinationBicyclePolicy'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (allowedNetworks != null)
          'allowedNetworks': allowedNetworks!.map((e) => e).toList(),
        if (bannedNetworks != null)
          'bannedNetworks': bannedNetworks!.map((e) => e).toList(),
        if (destinationBicyclePolicy != null)
          'destinationBicyclePolicy': destinationBicyclePolicy!.toJson(),
      };
}

class DestinationBicyclePolicyInput {
  final bool? allowKeeping;
  final int? keepingCost;

  const DestinationBicyclePolicyInput({this.allowKeeping, this.keepingCost});

  factory DestinationBicyclePolicyInput.fromJson(Map<String, dynamic> json) =>
      DestinationBicyclePolicyInput(
        allowKeeping: json['allowKeeping'] as bool?,
        keepingCost: (json['keepingCost'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        if (allowKeeping != null) 'allowKeeping': allowKeeping!,
        if (keepingCost != null) 'keepingCost': keepingCost!,
      };
}

class BicycleWalkPreferencesInput {
  final BicycleWalkPreferencesCostInput? cost;
  final String? mountDismountTime;
  final double? speed;

  const BicycleWalkPreferencesInput({
    this.cost,
    this.mountDismountTime,
    this.speed,
  });

  factory BicycleWalkPreferencesInput.fromJson(Map<String, dynamic> json) =>
      BicycleWalkPreferencesInput(
        cost: json['cost'] == null
            ? null
            : BicycleWalkPreferencesCostInput.fromJson(
                json['cost'] as Map<String, dynamic>,
              ),
        mountDismountTime: json['mountDismountTime'] as String?,
        speed: (json['speed'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        if (cost != null) 'cost': cost!.toJson(),
        if (mountDismountTime != null) 'mountDismountTime': mountDismountTime!,
        if (speed != null) 'speed': speed!,
      };
}

class BicycleWalkPreferencesCostInput {
  final int? mountDismountCost;
  final double? reluctance;

  const BicycleWalkPreferencesCostInput({
    this.mountDismountCost,
    this.reluctance,
  });

  factory BicycleWalkPreferencesCostInput.fromJson(Map<String, dynamic> json) =>
      BicycleWalkPreferencesCostInput(
        mountDismountCost: (json['mountDismountCost'] as num?)?.toInt(),
        reluctance: (json['reluctance'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        if (mountDismountCost != null) 'mountDismountCost': mountDismountCost!,
        if (reluctance != null) 'reluctance': reluctance!,
      };
}

class CarPreferencesInput {
  final int? boardCost;
  final CarParkingPreferencesInput? parking;
  final double? reluctance;
  final CarRentalPreferencesInput? rental;

  const CarPreferencesInput({
    this.boardCost,
    this.parking,
    this.reluctance,
    this.rental,
  });

  factory CarPreferencesInput.fromJson(Map<String, dynamic> json) =>
      CarPreferencesInput(
        boardCost: (json['boardCost'] as num?)?.toInt(),
        parking: json['parking'] == null
            ? null
            : CarParkingPreferencesInput.fromJson(
                json['parking'] as Map<String, dynamic>,
              ),
        reluctance: (json['reluctance'] as num?)?.toDouble(),
        rental: json['rental'] == null
            ? null
            : CarRentalPreferencesInput.fromJson(
                json['rental'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (boardCost != null) 'boardCost': boardCost!,
        if (parking != null) 'parking': parking!.toJson(),
        if (reluctance != null) 'reluctance': reluctance!,
        if (rental != null) 'rental': rental!.toJson(),
      };
}

class CarParkingPreferencesInput {
  final List<ParkingFilter>? filters;
  final List<ParkingFilter>? preferred;
  final int? unpreferredCost;

  const CarParkingPreferencesInput({
    this.filters,
    this.preferred,
    this.unpreferredCost,
  });

  factory CarParkingPreferencesInput.fromJson(Map<String, dynamic> json) =>
      CarParkingPreferencesInput(
        filters: (json['filters'] as List<dynamic>?)
            ?.map((e) => ParkingFilter.fromJson(e as Map<String, dynamic>))
            .toList(),
        preferred: (json['preferred'] as List<dynamic>?)
            ?.map((e) => ParkingFilter.fromJson(e as Map<String, dynamic>))
            .toList(),
        unpreferredCost: (json['unpreferredCost'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        if (filters != null)
          'filters': filters!.map((e) => e.toJson()).toList(),
        if (preferred != null)
          'preferred': preferred!.map((e) => e.toJson()).toList(),
        if (unpreferredCost != null) 'unpreferredCost': unpreferredCost!,
      };
}

class CarRentalPreferencesInput {
  final List<String>? allowedNetworks;
  final List<String>? bannedNetworks;
  final String? rentalDuration;

  const CarRentalPreferencesInput({
    this.allowedNetworks,
    this.bannedNetworks,
    this.rentalDuration,
  });

  factory CarRentalPreferencesInput.fromJson(Map<String, dynamic> json) =>
      CarRentalPreferencesInput(
        allowedNetworks: (json['allowedNetworks'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
        bannedNetworks: (json['bannedNetworks'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
        rentalDuration: json['rentalDuration'] as String?,
      );

  Map<String, dynamic> toJson() => {
        if (allowedNetworks != null)
          'allowedNetworks': allowedNetworks!.map((e) => e).toList(),
        if (bannedNetworks != null)
          'bannedNetworks': bannedNetworks!.map((e) => e).toList(),
        if (rentalDuration != null) 'rentalDuration': rentalDuration!,
      };
}

class ScooterPreferencesInput {
  final ScooterOptimizationInput? optimization;
  final double? reluctance;
  final ScooterRentalPreferencesInput? rental;
  final double? speed;

  const ScooterPreferencesInput({
    this.optimization,
    this.reluctance,
    this.rental,
    this.speed,
  });

  factory ScooterPreferencesInput.fromJson(Map<String, dynamic> json) =>
      ScooterPreferencesInput(
        optimization: json['optimization'] == null
            ? null
            : ScooterOptimizationInput.fromJson(
                json['optimization'] as Map<String, dynamic>,
              ),
        reluctance: (json['reluctance'] as num?)?.toDouble(),
        rental: json['rental'] == null
            ? null
            : ScooterRentalPreferencesInput.fromJson(
                json['rental'] as Map<String, dynamic>,
              ),
        speed: (json['speed'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        if (optimization != null) 'optimization': optimization!.toJson(),
        if (reluctance != null) 'reluctance': reluctance!,
        if (rental != null) 'rental': rental!.toJson(),
        if (speed != null) 'speed': speed!,
      };
}

class ScooterOptimizationInput {
  final TriangleScooterFactorsInput? triangle;
  final ScooterOptimizationType? type;

  const ScooterOptimizationInput({this.triangle, this.type});

  factory ScooterOptimizationInput.fromJson(Map<String, dynamic> json) =>
      ScooterOptimizationInput(
        triangle: json['triangle'] == null
            ? null
            : TriangleScooterFactorsInput.fromJson(
                json['triangle'] as Map<String, dynamic>,
              ),
        type: json['type'] == null
            ? null
            : ScooterOptimizationType.fromWire(json['type'] as String),
      );

  Map<String, dynamic> toJson() => {
        if (triangle != null) 'triangle': triangle!.toJson(),
        if (type != null) 'type': type!.toJson(),
      };
}

class TriangleScooterFactorsInput {
  final double flatness;
  final double safety;
  final double time;

  const TriangleScooterFactorsInput({
    required this.flatness,
    required this.safety,
    required this.time,
  });

  factory TriangleScooterFactorsInput.fromJson(Map<String, dynamic> json) =>
      TriangleScooterFactorsInput(
        flatness: (json['flatness'] as num).toDouble(),
        safety: (json['safety'] as num).toDouble(),
        time: (json['time'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'flatness': flatness,
        'safety': safety,
        'time': time,
      };
}

enum ScooterOptimizationType {
  flatStreets('FLAT_STREETS'),
  safestStreets('SAFEST_STREETS'),
  safeStreets('SAFE_STREETS'),
  shortestDuration('SHORTEST_DURATION'),
  unknown('UNKNOWN');

  const ScooterOptimizationType(this.wire);

  final String wire;

  static ScooterOptimizationType fromWire(String? value) {
    for (final e in ScooterOptimizationType.values) {
      if (e.wire == value) return e;
    }
    return ScooterOptimizationType.unknown;
  }

  String toJson() => wire;
}

class ScooterRentalPreferencesInput {
  final List<String>? allowedNetworks;
  final List<String>? bannedNetworks;
  final DestinationScooterPolicyInput? destinationScooterPolicy;

  const ScooterRentalPreferencesInput({
    this.allowedNetworks,
    this.bannedNetworks,
    this.destinationScooterPolicy,
  });

  factory ScooterRentalPreferencesInput.fromJson(Map<String, dynamic> json) =>
      ScooterRentalPreferencesInput(
        allowedNetworks: (json['allowedNetworks'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
        bannedNetworks: (json['bannedNetworks'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
        destinationScooterPolicy: json['destinationScooterPolicy'] == null
            ? null
            : DestinationScooterPolicyInput.fromJson(
                json['destinationScooterPolicy'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (allowedNetworks != null)
          'allowedNetworks': allowedNetworks!.map((e) => e).toList(),
        if (bannedNetworks != null)
          'bannedNetworks': bannedNetworks!.map((e) => e).toList(),
        if (destinationScooterPolicy != null)
          'destinationScooterPolicy': destinationScooterPolicy!.toJson(),
      };
}

class DestinationScooterPolicyInput {
  final bool? allowKeeping;
  final int? keepingCost;

  const DestinationScooterPolicyInput({this.allowKeeping, this.keepingCost});

  factory DestinationScooterPolicyInput.fromJson(Map<String, dynamic> json) =>
      DestinationScooterPolicyInput(
        allowKeeping: json['allowKeeping'] as bool?,
        keepingCost: (json['keepingCost'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        if (allowKeeping != null) 'allowKeeping': allowKeeping!,
        if (keepingCost != null) 'keepingCost': keepingCost!,
      };
}

class WalkPreferencesInput {
  final int? boardCost;
  final double? reluctance;
  final double? safetyFactor;
  final double? speed;

  const WalkPreferencesInput({
    this.boardCost,
    this.reluctance,
    this.safetyFactor,
    this.speed,
  });

  factory WalkPreferencesInput.fromJson(Map<String, dynamic> json) =>
      WalkPreferencesInput(
        boardCost: (json['boardCost'] as num?)?.toInt(),
        reluctance: (json['reluctance'] as num?)?.toDouble(),
        safetyFactor: (json['safetyFactor'] as num?)?.toDouble(),
        speed: (json['speed'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        if (boardCost != null) 'boardCost': boardCost!,
        if (reluctance != null) 'reluctance': reluctance!,
        if (safetyFactor != null) 'safetyFactor': safetyFactor!,
        if (speed != null) 'speed': speed!,
      };
}

class TransitPreferencesInput {
  final AlightPreferencesInput? alight;
  final BoardPreferencesInput? board;
  final List<TransitFilterInput>? filters;
  final TimetablePreferencesInput? timetable;
  final TransferPreferencesInput? transfer;

  const TransitPreferencesInput({
    this.alight,
    this.board,
    this.filters,
    this.timetable,
    this.transfer,
  });

  factory TransitPreferencesInput.fromJson(Map<String, dynamic> json) =>
      TransitPreferencesInput(
        alight: json['alight'] == null
            ? null
            : AlightPreferencesInput.fromJson(
                json['alight'] as Map<String, dynamic>,
              ),
        board: json['board'] == null
            ? null
            : BoardPreferencesInput.fromJson(
                json['board'] as Map<String, dynamic>,
              ),
        filters: (json['filters'] as List<dynamic>?)
            ?.map((e) => TransitFilterInput.fromJson(e as Map<String, dynamic>))
            .toList(),
        timetable: json['timetable'] == null
            ? null
            : TimetablePreferencesInput.fromJson(
                json['timetable'] as Map<String, dynamic>,
              ),
        transfer: json['transfer'] == null
            ? null
            : TransferPreferencesInput.fromJson(
                json['transfer'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (alight != null) 'alight': alight!.toJson(),
        if (board != null) 'board': board!.toJson(),
        if (filters != null)
          'filters': filters!.map((e) => e.toJson()).toList(),
        if (timetable != null) 'timetable': timetable!.toJson(),
        if (transfer != null) 'transfer': transfer!.toJson(),
      };
}

class AlightPreferencesInput {
  final String? slack;

  const AlightPreferencesInput({this.slack});

  factory AlightPreferencesInput.fromJson(Map<String, dynamic> json) =>
      AlightPreferencesInput(slack: json['slack'] as String?);

  Map<String, dynamic> toJson() => {if (slack != null) 'slack': slack!};
}

class BoardPreferencesInput {
  final String? slack;
  final double? waitReluctance;

  const BoardPreferencesInput({this.slack, this.waitReluctance});

  factory BoardPreferencesInput.fromJson(Map<String, dynamic> json) =>
      BoardPreferencesInput(
        slack: json['slack'] as String?,
        waitReluctance: (json['waitReluctance'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        if (slack != null) 'slack': slack!,
        if (waitReluctance != null) 'waitReluctance': waitReluctance!,
      };
}

class TransitFilterInput {
  final List<TransitFilterSelectInput>? exclude;
  final List<TransitFilterSelectInput>? include;

  const TransitFilterInput({this.exclude, this.include});

  factory TransitFilterInput.fromJson(Map<String, dynamic> json) =>
      TransitFilterInput(
        exclude: (json['exclude'] as List<dynamic>?)
            ?.map(
              (e) =>
                  TransitFilterSelectInput.fromJson(e as Map<String, dynamic>),
            )
            .toList(),
        include: (json['include'] as List<dynamic>?)
            ?.map(
              (e) =>
                  TransitFilterSelectInput.fromJson(e as Map<String, dynamic>),
            )
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (exclude != null)
          'exclude': exclude!.map((e) => e.toJson()).toList(),
        if (include != null)
          'include': include!.map((e) => e.toJson()).toList(),
      };
}

class TransitFilterSelectInput {
  final List<String>? agencies;
  final List<String>? routes;

  const TransitFilterSelectInput({this.agencies, this.routes});

  factory TransitFilterSelectInput.fromJson(Map<String, dynamic> json) =>
      TransitFilterSelectInput(
        agencies: (json['agencies'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
        routes: (json['routes'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (agencies != null) 'agencies': agencies!.map((e) => e).toList(),
        if (routes != null) 'routes': routes!.map((e) => e).toList(),
      };
}

class TimetablePreferencesInput {
  final bool? excludeRealTimeUpdates;
  final bool? includePlannedCancellations;
  final bool? includeRealTimeCancellations;

  const TimetablePreferencesInput({
    this.excludeRealTimeUpdates,
    this.includePlannedCancellations,
    this.includeRealTimeCancellations,
  });

  factory TimetablePreferencesInput.fromJson(
    Map<String, dynamic> json,
  ) =>
      TimetablePreferencesInput(
        excludeRealTimeUpdates: json['excludeRealTimeUpdates'] as bool?,
        includePlannedCancellations:
            json['includePlannedCancellations'] as bool?,
        includeRealTimeCancellations:
            json['includeRealTimeCancellations'] as bool?,
      );

  Map<String, dynamic> toJson() => {
        if (excludeRealTimeUpdates != null)
          'excludeRealTimeUpdates': excludeRealTimeUpdates!,
        if (includePlannedCancellations != null)
          'includePlannedCancellations': includePlannedCancellations!,
        if (includeRealTimeCancellations != null)
          'includeRealTimeCancellations': includeRealTimeCancellations!,
      };
}

class TransferPreferencesInput {
  final int? cost;
  final int? maximumAdditionalTransfers;
  final int? maximumTransfers;
  final String? slack;

  const TransferPreferencesInput({
    this.cost,
    this.maximumAdditionalTransfers,
    this.maximumTransfers,
    this.slack,
  });

  factory TransferPreferencesInput.fromJson(Map<String, dynamic> json) =>
      TransferPreferencesInput(
        cost: (json['cost'] as num?)?.toInt(),
        maximumAdditionalTransfers:
            (json['maximumAdditionalTransfers'] as num?)?.toInt(),
        maximumTransfers: (json['maximumTransfers'] as num?)?.toInt(),
        slack: json['slack'] as String?,
      );

  Map<String, dynamic> toJson() => {
        if (cost != null) 'cost': cost!,
        if (maximumAdditionalTransfers != null)
          'maximumAdditionalTransfers': maximumAdditionalTransfers!,
        if (maximumTransfers != null) 'maximumTransfers': maximumTransfers!,
        if (slack != null) 'slack': slack!,
      };
}

class PlanConnectionVariables {
  final PlanDateTimeInput dateTime;
  final PlanLabeledLocationInput origin;
  final PlanLabeledLocationInput destination;
  final List<PlanViaLocationInput>? via;
  final PlanModesInput? modes;
  final PlanPreferencesInput? preferences;
  final String? searchWindow;
  final int? first;
  final int? last;
  final String? before;
  final String? after;

  const PlanConnectionVariables({
    required this.dateTime,
    required this.origin,
    required this.destination,
    this.via,
    this.modes,
    this.preferences,
    this.searchWindow,
    this.first,
    this.last,
    this.before,
    this.after,
  });

  factory PlanConnectionVariables.fromJson(Map<String, dynamic> json) =>
      PlanConnectionVariables(
        dateTime: PlanDateTimeInput.fromJson(
          json['dateTime'] as Map<String, dynamic>,
        ),
        origin: PlanLabeledLocationInput.fromJson(
          json['origin'] as Map<String, dynamic>,
        ),
        destination: PlanLabeledLocationInput.fromJson(
          json['destination'] as Map<String, dynamic>,
        ),
        via: (json['via'] as List<dynamic>?)
            ?.map(
              (e) => PlanViaLocationInput.fromJson(e as Map<String, dynamic>),
            )
            .toList(),
        modes: json['modes'] == null
            ? null
            : PlanModesInput.fromJson(json['modes'] as Map<String, dynamic>),
        preferences: json['preferences'] == null
            ? null
            : PlanPreferencesInput.fromJson(
                json['preferences'] as Map<String, dynamic>,
              ),
        searchWindow: json['searchWindow'] as String?,
        first: (json['first'] as num?)?.toInt(),
        last: (json['last'] as num?)?.toInt(),
        before: json['before'] as String?,
        after: json['after'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'dateTime': dateTime.toJson(),
        'origin': origin.toJson(),
        'destination': destination.toJson(),
        if (via != null) 'via': via!.map((e) => e.toJson()).toList(),
        if (modes != null) 'modes': modes!.toJson(),
        if (preferences != null) 'preferences': preferences!.toJson(),
        if (searchWindow != null) 'searchWindow': searchWindow!,
        if (first != null) 'first': first!,
        if (last != null) 'last': last!,
        if (before != null) 'before': before!,
        if (after != null) 'after': after!,
      };
}

class StopDeparturesRoute {
  final String? shortName;
  final String? longName;
  final TransitMode? mode;

  const StopDeparturesRoute({this.shortName, this.longName, this.mode});

  factory StopDeparturesRoute.fromJson(Map<String, dynamic> json) =>
      StopDeparturesRoute(
        shortName: json['shortName'] as String?,
        longName: json['longName'] as String?,
        mode: json['mode'] == null
            ? null
            : TransitMode.fromWire(json['mode'] as String),
      );

  Map<String, dynamic> toJson() => {
        if (shortName != null) 'shortName': shortName!,
        if (longName != null) 'longName': longName!,
        if (mode != null) 'mode': mode!.toJson(),
      };
}

class StopDeparturesTrip {
  final String gtfsId;
  final StopDeparturesRoute route;
  final BikesAllowed? bikesAllowed;

  const StopDeparturesTrip({
    required this.gtfsId,
    required this.route,
    this.bikesAllowed,
  });

  factory StopDeparturesTrip.fromJson(Map<String, dynamic> json) =>
      StopDeparturesTrip(
        gtfsId: json['gtfsId'] as String,
        route: StopDeparturesRoute.fromJson(
          json['route'] as Map<String, dynamic>,
        ),
        bikesAllowed: json['bikesAllowed'] == null
            ? null
            : BikesAllowed.fromWire(json['bikesAllowed'] as String),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        'route': route.toJson(),
        if (bikesAllowed != null) 'bikesAllowed': bikesAllowed!.toJson(),
      };
}

class Stoptime {
  final int? serviceDay;
  final int? scheduledDeparture;
  final int? realtimeDeparture;
  final bool? realtime;
  final RealtimeState? realtimeState;
  final String? headsign;
  final StopDeparturesTrip? trip;

  const Stoptime({
    this.serviceDay,
    this.scheduledDeparture,
    this.realtimeDeparture,
    this.realtime,
    this.realtimeState,
    this.headsign,
    this.trip,
  });

  factory Stoptime.fromJson(Map<String, dynamic> json) => Stoptime(
        serviceDay: (json['serviceDay'] as num?)?.toInt(),
        scheduledDeparture: (json['scheduledDeparture'] as num?)?.toInt(),
        realtimeDeparture: (json['realtimeDeparture'] as num?)?.toInt(),
        realtime: json['realtime'] as bool?,
        realtimeState: json['realtimeState'] == null
            ? null
            : RealtimeState.fromWire(json['realtimeState'] as String),
        headsign: json['headsign'] as String?,
        trip: json['trip'] == null
            ? null
            : StopDeparturesTrip.fromJson(json['trip'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (serviceDay != null) 'serviceDay': serviceDay!,
        if (scheduledDeparture != null)
          'scheduledDeparture': scheduledDeparture!,
        if (realtimeDeparture != null) 'realtimeDeparture': realtimeDeparture!,
        if (realtime != null) 'realtime': realtime!,
        if (realtimeState != null) 'realtimeState': realtimeState!.toJson(),
        if (headsign != null) 'headsign': headsign!,
        if (trip != null) 'trip': trip!.toJson(),
      };
}

class StopDeparturesStop {
  final String gtfsId;
  final String name;
  final WheelchairBoarding? wheelchairBoarding;
  final List<Stoptime>? stoptimesWithoutPatterns;

  const StopDeparturesStop({
    required this.gtfsId,
    required this.name,
    this.wheelchairBoarding,
    this.stoptimesWithoutPatterns,
  });

  factory StopDeparturesStop.fromJson(Map<String, dynamic> json) =>
      StopDeparturesStop(
        gtfsId: json['gtfsId'] as String,
        name: json['name'] as String,
        wheelchairBoarding: json['wheelchairBoarding'] == null
            ? null
            : WheelchairBoarding.fromWire(json['wheelchairBoarding'] as String),
        stoptimesWithoutPatterns:
            (json['stoptimesWithoutPatterns'] as List<dynamic>?)
                ?.map((e) => Stoptime.fromJson(e as Map<String, dynamic>))
                .toList(),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        'name': name,
        if (wheelchairBoarding != null)
          'wheelchairBoarding': wheelchairBoarding!.toJson(),
        if (stoptimesWithoutPatterns != null)
          'stoptimesWithoutPatterns':
              stoptimesWithoutPatterns!.map((e) => e.toJson()).toList(),
      };
}

class StopDeparturesData {
  final StopDeparturesStop? asStop;
  final StopDeparturesStop? asStation;

  const StopDeparturesData({this.asStop, this.asStation});

  factory StopDeparturesData.fromJson(Map<String, dynamic> json) =>
      StopDeparturesData(
        asStop: json['asStop'] == null
            ? null
            : StopDeparturesStop.fromJson(
                json['asStop'] as Map<String, dynamic>,
              ),
        asStation: json['asStation'] == null
            ? null
            : StopDeparturesStop.fromJson(
                json['asStation'] as Map<String, dynamic>,
              ),
      );

  Map<String, dynamic> toJson() => {
        if (asStop != null) 'asStop': asStop!.toJson(),
        if (asStation != null) 'asStation': asStation!.toJson(),
      };
}

class StopDeparturesResponse {
  final StopDeparturesData? data;
  final List<GraphQLError>? errors;

  const StopDeparturesResponse({this.data, this.errors});

  factory StopDeparturesResponse.fromJson(Map<String, dynamic> json) =>
      StopDeparturesResponse(
        data: json['data'] == null
            ? null
            : StopDeparturesData.fromJson(json['data'] as Map<String, dynamic>),
        errors: (json['errors'] as List<dynamic>?)
            ?.map((e) => GraphQLError.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (data != null) 'data': data!.toJson(),
        if (errors != null) 'errors': errors!.map((e) => e.toJson()).toList(),
      };
}

class StopDeparturesVariables {
  final String id;
  final int? numberOfDepartures;
  final int? startTime;
  final int? timeRange;

  const StopDeparturesVariables({
    required this.id,
    this.numberOfDepartures,
    this.startTime,
    this.timeRange,
  });

  factory StopDeparturesVariables.fromJson(Map<String, dynamic> json) =>
      StopDeparturesVariables(
        id: json['id'] as String,
        numberOfDepartures: (json['numberOfDepartures'] as num?)?.toInt(),
        startTime: (json['startTime'] as num?)?.toInt(),
        timeRange: (json['timeRange'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        if (numberOfDepartures != null)
          'numberOfDepartures': numberOfDepartures!,
        if (startTime != null) 'startTime': startTime!,
        if (timeRange != null) 'timeRange': timeRange!,
      };
}

class TripRoute {
  final String? shortName;
  final String? longName;
  final TransitMode? mode;

  const TripRoute({this.shortName, this.longName, this.mode});

  factory TripRoute.fromJson(Map<String, dynamic> json) => TripRoute(
        shortName: json['shortName'] as String?,
        longName: json['longName'] as String?,
        mode: json['mode'] == null
            ? null
            : TransitMode.fromWire(json['mode'] as String),
      );

  Map<String, dynamic> toJson() => {
        if (shortName != null) 'shortName': shortName!,
        if (longName != null) 'longName': longName!,
        if (mode != null) 'mode': mode!.toJson(),
      };
}

class TripStop {
  final String gtfsId;
  final String name;
  final double? lat;
  final double? lon;
  final WheelchairBoarding? wheelchairBoarding;

  const TripStop({
    required this.gtfsId,
    required this.name,
    this.lat,
    this.lon,
    this.wheelchairBoarding,
  });

  factory TripStop.fromJson(Map<String, dynamic> json) => TripStop(
        gtfsId: json['gtfsId'] as String,
        name: json['name'] as String,
        lat: (json['lat'] as num?)?.toDouble(),
        lon: (json['lon'] as num?)?.toDouble(),
        wheelchairBoarding: json['wheelchairBoarding'] == null
            ? null
            : WheelchairBoarding.fromWire(json['wheelchairBoarding'] as String),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        'name': name,
        if (lat != null) 'lat': lat!,
        if (lon != null) 'lon': lon!,
        if (wheelchairBoarding != null)
          'wheelchairBoarding': wheelchairBoarding!.toJson(),
      };
}

class TripStoptime {
  final int? serviceDay;
  final int? scheduledArrival;
  final int? scheduledDeparture;
  final int? realtimeArrival;
  final int? realtimeDeparture;
  final bool? realtime;
  final RealtimeState? realtimeState;
  final TripStop? stop;

  const TripStoptime({
    this.serviceDay,
    this.scheduledArrival,
    this.scheduledDeparture,
    this.realtimeArrival,
    this.realtimeDeparture,
    this.realtime,
    this.realtimeState,
    this.stop,
  });

  factory TripStoptime.fromJson(Map<String, dynamic> json) => TripStoptime(
        serviceDay: (json['serviceDay'] as num?)?.toInt(),
        scheduledArrival: (json['scheduledArrival'] as num?)?.toInt(),
        scheduledDeparture: (json['scheduledDeparture'] as num?)?.toInt(),
        realtimeArrival: (json['realtimeArrival'] as num?)?.toInt(),
        realtimeDeparture: (json['realtimeDeparture'] as num?)?.toInt(),
        realtime: json['realtime'] as bool?,
        realtimeState: json['realtimeState'] == null
            ? null
            : RealtimeState.fromWire(json['realtimeState'] as String),
        stop: json['stop'] == null
            ? null
            : TripStop.fromJson(json['stop'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (serviceDay != null) 'serviceDay': serviceDay!,
        if (scheduledArrival != null) 'scheduledArrival': scheduledArrival!,
        if (scheduledDeparture != null)
          'scheduledDeparture': scheduledDeparture!,
        if (realtimeArrival != null) 'realtimeArrival': realtimeArrival!,
        if (realtimeDeparture != null) 'realtimeDeparture': realtimeDeparture!,
        if (realtime != null) 'realtime': realtime!,
        if (realtimeState != null) 'realtimeState': realtimeState!.toJson(),
        if (stop != null) 'stop': stop!.toJson(),
      };
}

class TripGeometry {
  final String? points;
  final int? length;

  const TripGeometry({this.points, this.length});

  factory TripGeometry.fromJson(Map<String, dynamic> json) => TripGeometry(
        points: json['points'] as String?,
        length: (json['length'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        if (points != null) 'points': points!,
        if (length != null) 'length': length!,
      };
}

class TripTrip {
  final String gtfsId;
  final TripRoute route;
  final String? directionId;
  final String? tripHeadsign;
  final BikesAllowed? bikesAllowed;
  final List<TripStoptime>? stoptimesForDate;
  final TripGeometry? tripGeometry;

  const TripTrip({
    required this.gtfsId,
    required this.route,
    this.directionId,
    this.tripHeadsign,
    this.bikesAllowed,
    this.stoptimesForDate,
    this.tripGeometry,
  });

  factory TripTrip.fromJson(Map<String, dynamic> json) => TripTrip(
        gtfsId: json['gtfsId'] as String,
        route: TripRoute.fromJson(json['route'] as Map<String, dynamic>),
        directionId: json['directionId'] as String?,
        tripHeadsign: json['tripHeadsign'] as String?,
        bikesAllowed: json['bikesAllowed'] == null
            ? null
            : BikesAllowed.fromWire(json['bikesAllowed'] as String),
        stoptimesForDate: (json['stoptimesForDate'] as List<dynamic>?)
            ?.map((e) => TripStoptime.fromJson(e as Map<String, dynamic>))
            .toList(),
        tripGeometry: json['tripGeometry'] == null
            ? null
            : TripGeometry.fromJson(
                json['tripGeometry'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        'route': route.toJson(),
        if (directionId != null) 'directionId': directionId!,
        if (tripHeadsign != null) 'tripHeadsign': tripHeadsign!,
        if (bikesAllowed != null) 'bikesAllowed': bikesAllowed!.toJson(),
        if (stoptimesForDate != null)
          'stoptimesForDate': stoptimesForDate!.map((e) => e.toJson()).toList(),
        if (tripGeometry != null) 'tripGeometry': tripGeometry!.toJson(),
      };
}

class TripData {
  final TripTrip? trip;

  const TripData({this.trip});

  factory TripData.fromJson(Map<String, dynamic> json) => TripData(
        trip: json['trip'] == null
            ? null
            : TripTrip.fromJson(json['trip'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {if (trip != null) 'trip': trip!.toJson()};
}

class TripResponse {
  final TripData? data;
  final List<GraphQLError>? errors;

  const TripResponse({this.data, this.errors});

  factory TripResponse.fromJson(Map<String, dynamic> json) => TripResponse(
        data: json['data'] == null
            ? null
            : TripData.fromJson(json['data'] as Map<String, dynamic>),
        errors: (json['errors'] as List<dynamic>?)
            ?.map((e) => GraphQLError.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (data != null) 'data': data!.toJson(),
        if (errors != null) 'errors': errors!.map((e) => e.toJson()).toList(),
      };
}

class TripVariables {
  final String id;
  final String? serviceDate;

  const TripVariables({required this.id, this.serviceDate});

  factory TripVariables.fromJson(Map<String, dynamic> json) => TripVariables(
        id: json['id'] as String,
        serviceDate: json['serviceDate'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        if (serviceDate != null) 'serviceDate': serviceDate!,
      };
}

/// Standard error body: a stable machine-readable `code` and a human-readable `message`.
class ErrorResponse {
  final String message;
  final String? code;

  const ErrorResponse({required this.message, this.code});

  factory ErrorResponse.fromJson(Map<String, dynamic> json) => ErrorResponse(
        message: json['message'] as String,
        code: json['code'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'message': message,
        if (code != null) 'code': code!,
      };
}
