// GENERATED by spider-codegen — do not edit. Regenerate via scripts/generate-contract.sh.

/// POST body for `/routing/plan`: one page of itineraries. Paging: `before` and `after` are exclusive. Use `first` with `after` or with no cursor, and `last` only with `before`. The next page is the same body plus `after` (the page's `pageInfo.endCursor`), sized by `first`. The previous page is the same body without `first` and `after`, plus `before` (`pageInfo.startCursor`), sized by `last`. Any other pairing is a 400 naming the member that breaks it. A key not listed here, at any depth, is a 400 `<path> is not allowed`. Every bound is rejected, never clamped. `null` on an optional member means absent.
class PlanTripRequest {
  final PlanDateTimeInput dateTime;

  /// Where the journey starts. An unknown stop id is a 200 with the `routingErrors` code `LOCATION_NOT_FOUND` on `FROM`.
  final PlanLabeledLocationInput origin;

  /// Where the journey ends. An unknown stop id is a 200 with the `routingErrors` code `LOCATION_NOT_FOUND` on `TO`.
  final PlanLabeledLocationInput destination;

  /// How much time after `dateTime` the search covers (before it, for `latestArrival`), as an ISO-8601 duration such as `PT2H`: above zero and at most the environment's search-window limit; rejected, never clamped.
  final String searchWindow;

  /// Locations the journey must visit or pass through, in the order given. How many a request takes is an environment setting, and an environment set to 0 has via turned off; more is a 400 naming `via`. An unknown via stop id is a 200 with the `routingErrors` code `LOCATION_NOT_FOUND` on `VIA`.
  final List<PlanViaLocationInput>? via;
  final PlanModesInput? modes;
  final PlanPreferencesInput? preferences;

  /// Itineraries on this page: 1 up to the environment's itinerary limit; rejected, never clamped. Absent means the limit. With `after` or no cursor, never with `before`.
  final int? first;

  /// Itineraries on the previous page: 1 up to the environment's itinerary limit; rejected, never clamped. Absent means the limit. Only with `before`.
  final int? last;

  /// `pageInfo.startCursor` of a page, to fetch the page before it. Never with `after`.
  final String? before;

  /// `pageInfo.endCursor` of a page, to fetch the page after it. Never with `before`.
  final String? after;

  /// Delay-aware planning level; omitted or null plans on the timetable alone.
  final Reliability? reliability;

  const PlanTripRequest({
    required this.dateTime,
    required this.origin,
    required this.destination,
    required this.searchWindow,
    this.via,
    this.modes,
    this.preferences,
    this.first,
    this.last,
    this.before,
    this.after,
    this.reliability,
  });

  factory PlanTripRequest.fromJson(Map<String, dynamic> json) =>
      PlanTripRequest(
        dateTime: PlanDateTimeInput.fromJson(
            json['dateTime'] as Map<String, dynamic>),
        origin: PlanLabeledLocationInput.fromJson(
            json['origin'] as Map<String, dynamic>),
        destination: PlanLabeledLocationInput.fromJson(
            json['destination'] as Map<String, dynamic>),
        searchWindow: json['searchWindow'] as String,
        via: (json['via'] as List<dynamic>?)
            ?.map(
                (e) => PlanViaLocationInput.fromJson(e as Map<String, dynamic>))
            .toList(),
        modes: json['modes'] == null
            ? null
            : PlanModesInput.fromJson(json['modes'] as Map<String, dynamic>),
        preferences: json['preferences'] == null
            ? null
            : PlanPreferencesInput.fromJson(
                json['preferences'] as Map<String, dynamic>),
        first: (json['first'] as num?)?.toInt(),
        last: (json['last'] as num?)?.toInt(),
        before: json['before'] as String?,
        after: json['after'] as String?,
        reliability: json['reliability'] == null
            ? null
            : Reliability.fromWire(json['reliability'] as String),
      );

  Map<String, dynamic> toJson() => {
        'dateTime': dateTime.toJson(),
        'origin': origin.toJson(),
        'destination': destination.toJson(),
        'searchWindow': searchWindow,
        if (via != null) 'via': via!.map((e) => e.toJson()).toList(),
        if (modes != null) 'modes': modes!.toJson(),
        if (preferences != null) 'preferences': preferences!.toJson(),
        if (first != null) 'first': first!,
        if (last != null) 'last': last!,
        if (before != null) 'before': before!,
        if (after != null) 'after': after!,
        if (reliability != null) 'reliability': reliability!.toJson(),
      };
}

/// POST body for `/routing/plan-stream`: the Plan Trip search, streamed. Instead of a fixed window, the stream widens its search until it has sent `targetResults` itineraries or has searched `maxWindow`. To continue, send the `pageInfo` event's `endCursor` as `after` (later) or its `startCursor` as `before` (earlier); `before` and `after` are exclusive. A key not listed here, at any depth, is a 400 `<path> is not allowed`. Every bound is rejected, never clamped. `null` on an optional member means absent.
class PlanStreamRequest {
  final PlanDateTimeInput dateTime;

  /// Where the journey starts. An unknown stop id is a 200 with the `routingErrors` code `LOCATION_NOT_FOUND` on `FROM`.
  final PlanLabeledLocationInput origin;

  /// Where the journey ends. An unknown stop id is a 200 with the `routingErrors` code `LOCATION_NOT_FOUND` on `TO`.
  final PlanLabeledLocationInput destination;

  /// The stream stops once it has sent this many itineraries: 1 up to the environment's itinerary limit; rejected, never clamped.
  final int targetResults;

  /// The stream stops once it has searched this far past `dateTime` (before it, for `latestArrival`), as an ISO-8601 duration: at least `PT2H` and at most the environment's search-window limit; rejected, never clamped.
  final String maxWindow;

  /// Locations the journey must visit or pass through, in the order given. How many a request takes is an environment setting, and an environment set to 0 has via turned off; more is a 400 naming `via`. An unknown via stop id is a 200 with the `routingErrors` code `LOCATION_NOT_FOUND` on `VIA`.
  final List<PlanViaLocationInput>? via;
  final PlanModesInput? modes;
  final PlanPreferencesInput? preferences;

  /// `pageInfo.startCursor` of a page, to fetch the page before it. Never with `after`.
  final String? before;

  /// `pageInfo.endCursor` of a page, to fetch the page after it. Never with `before`.
  final String? after;

  /// Delay-aware planning level; omitted or null plans on the timetable alone.
  final Reliability? reliability;

  const PlanStreamRequest({
    required this.dateTime,
    required this.origin,
    required this.destination,
    required this.targetResults,
    required this.maxWindow,
    this.via,
    this.modes,
    this.preferences,
    this.before,
    this.after,
    this.reliability,
  });

  factory PlanStreamRequest.fromJson(Map<String, dynamic> json) =>
      PlanStreamRequest(
        dateTime: PlanDateTimeInput.fromJson(
            json['dateTime'] as Map<String, dynamic>),
        origin: PlanLabeledLocationInput.fromJson(
            json['origin'] as Map<String, dynamic>),
        destination: PlanLabeledLocationInput.fromJson(
            json['destination'] as Map<String, dynamic>),
        targetResults: (json['targetResults'] as num).toInt(),
        maxWindow: json['maxWindow'] as String,
        via: (json['via'] as List<dynamic>?)
            ?.map(
                (e) => PlanViaLocationInput.fromJson(e as Map<String, dynamic>))
            .toList(),
        modes: json['modes'] == null
            ? null
            : PlanModesInput.fromJson(json['modes'] as Map<String, dynamic>),
        preferences: json['preferences'] == null
            ? null
            : PlanPreferencesInput.fromJson(
                json['preferences'] as Map<String, dynamic>),
        before: json['before'] as String?,
        after: json['after'] as String?,
        reliability: json['reliability'] == null
            ? null
            : Reliability.fromWire(json['reliability'] as String),
      );

  Map<String, dynamic> toJson() => {
        'dateTime': dateTime.toJson(),
        'origin': origin.toJson(),
        'destination': destination.toJson(),
        'targetResults': targetResults,
        'maxWindow': maxWindow,
        if (via != null) 'via': via!.map((e) => e.toJson()).toList(),
        if (modes != null) 'modes': modes!.toJson(),
        if (preferences != null) 'preferences': preferences!.toJson(),
        if (before != null) 'before': before!,
        if (after != null) 'after': after!,
        if (reliability != null) 'reliability': reliability!.toJson(),
      };
}

/// POST body for `/routing/departures`. A key not listed here is a 400 `<key> is not allowed`. Every bound is rejected, never clamped.
class DeparturesRequest {
  /// Feed-prefixed id (`<feedId>:<id>`) of a stop, for that platform's board, or of a station, for all its platforms.
  final String id;

  /// Most rows on the board: 1 up to the environment's limit; rejected, never clamped.
  final int numberOfDepartures;

  /// Seconds after `startTime` the board covers: 1 to 86400 (24 hours); rejected, never clamped.
  final int timeRange;

  /// Unix seconds the board starts at. Absent or 0 means now.
  final int? startTime;

  const DeparturesRequest({
    required this.id,
    required this.numberOfDepartures,
    required this.timeRange,
    this.startTime,
  });

  factory DeparturesRequest.fromJson(Map<String, dynamic> json) =>
      DeparturesRequest(
        id: json['id'] as String,
        numberOfDepartures: (json['numberOfDepartures'] as num).toInt(),
        timeRange: (json['timeRange'] as num).toInt(),
        startTime: (json['startTime'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'numberOfDepartures': numberOfDepartures,
        'timeRange': timeRange,
        if (startTime != null) 'startTime': startTime!,
      };
}

/// POST body for `/routing/trip`. A key not listed here is a 400 `<key> is not allowed`.
class TripRequest {
  /// Feed-prefixed trip id (`<feedId>:<id>`).
  final String id;

  /// The service date, `YYYY-MM-DD` (`YYYYMMDD` also works). Absent means today in the feed's time zone. A value that is not a real date is a 400 naming `serviceDate`.
  final String? serviceDate;

  const TripRequest({
    required this.id,
    this.serviceDate,
  });

  factory TripRequest.fromJson(Map<String, dynamic> json) => TripRequest(
        id: json['id'] as String,
        serviceDate: json['serviceDate'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        if (serviceDate != null) 'serviceDate': serviceDate!,
      };
}

/// Exactly one of `earliestDeparture`, `latestArrival`. Both are RFC 3339 date-times with an offset, e.g. `2026-10-07T08:00:00+02:00`.
class PlanDateTimeInput {
  /// Depart at or after this time.
  final String? earliestDeparture;

  /// Arrive at or before this time.
  final String? latestArrival;

  const PlanDateTimeInput({
    this.earliestDeparture,
    this.latestArrival,
  });

  factory PlanDateTimeInput.fromJson(Map<String, dynamic> json) =>
      PlanDateTimeInput(
        earliestDeparture: json['earliestDeparture'] as String?,
        latestArrival: json['latestArrival'] as String?,
      );

  Map<String, dynamic> toJson() => {
        if (earliestDeparture != null) 'earliestDeparture': earliestDeparture!,
        if (latestArrival != null) 'latestArrival': latestArrival!,
      };
}

/// An origin or destination.
class PlanLabeledLocationInput {
  final PlanLocationInput location;

  const PlanLabeledLocationInput({
    required this.location,
  });

  factory PlanLabeledLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanLabeledLocationInput(
        location: PlanLocationInput.fromJson(
            json['location'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'location': location.toJson(),
      };
}

/// Exactly one of `coordinate`, `stopLocation`.
class PlanLocationInput {
  /// A point; the journey walks between it and the stops.
  final PlanCoordinateInput? coordinate;

  /// A stop or a station.
  final PlanStopLocationInput? stopLocation;

  const PlanLocationInput({
    this.coordinate,
    this.stopLocation,
  });

  factory PlanLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanLocationInput(
        coordinate: json['coordinate'] == null
            ? null
            : PlanCoordinateInput.fromJson(
                json['coordinate'] as Map<String, dynamic>),
        stopLocation: json['stopLocation'] == null
            ? null
            : PlanStopLocationInput.fromJson(
                json['stopLocation'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (coordinate != null) 'coordinate': coordinate!.toJson(),
        if (stopLocation != null) 'stopLocation': stopLocation!.toJson(),
      };
}

/// A WGS84 point.
class PlanCoordinateInput {
  /// Latitude in degrees.
  final double latitude;

  /// Longitude in degrees.
  final double longitude;

  const PlanCoordinateInput({
    required this.latitude,
    required this.longitude,
  });

  factory PlanCoordinateInput.fromJson(Map<String, dynamic> json) =>
      PlanCoordinateInput(
        latitude: (json['latitude'] as num).toDouble(),
        longitude: (json['longitude'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'latitude': latitude,
        'longitude': longitude,
      };
}

/// A stop or a station.
class PlanStopLocationInput {
  /// Feed-prefixed id of a stop or station (`<feedId>:<id>`).
  final String stopLocationId;

  const PlanStopLocationInput({
    required this.stopLocationId,
  });

  factory PlanStopLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanStopLocationInput(
        stopLocationId: json['stopLocationId'] as String,
      );

  Map<String, dynamic> toJson() => {
        'stopLocationId': stopLocationId,
      };
}

/// Exactly one of `passThrough`, `visit`.
class PlanViaLocationInput {
  /// The journey passes the location, on board or by changing vehicles there.
  final PlanPassThroughViaLocationInput? passThrough;

  /// The journey stops at the location: it alights there and boards again after `minimumWaitTime`.
  final PlanVisitViaLocationInput? visit;

  const PlanViaLocationInput({
    this.passThrough,
    this.visit,
  });

  factory PlanViaLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanViaLocationInput(
        passThrough: json['passThrough'] == null
            ? null
            : PlanPassThroughViaLocationInput.fromJson(
                json['passThrough'] as Map<String, dynamic>),
        visit: json['visit'] == null
            ? null
            : PlanVisitViaLocationInput.fromJson(
                json['visit'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (passThrough != null) 'passThrough': passThrough!.toJson(),
        if (visit != null) 'visit': visit!.toJson(),
      };
}

/// A location the journey stops at.
class PlanVisitViaLocationInput {
  /// 1 to 10 feed-prefixed stop or station ids; visiting any one of them is enough. Absent, empty, or more than 10 is a 400 naming `via`.
  final List<String>? stopLocationIds;

  /// Least time to stay at the location, as an ISO-8601 duration: `PT0S` to `PT1H`; rejected, never clamped. Absent means `PT0S`.
  final String? minimumWaitTime;

  const PlanVisitViaLocationInput({
    this.stopLocationIds,
    this.minimumWaitTime,
  });

  factory PlanVisitViaLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanVisitViaLocationInput(
        stopLocationIds: (json['stopLocationIds'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
        minimumWaitTime: json['minimumWaitTime'] as String?,
      );

  Map<String, dynamic> toJson() => {
        if (stopLocationIds != null)
          'stopLocationIds': stopLocationIds!.map((e) => e).toList(),
        if (minimumWaitTime != null) 'minimumWaitTime': minimumWaitTime!,
      };
}

/// A location the journey passes.
class PlanPassThroughViaLocationInput {
  /// 1 to 10 feed-prefixed stop or station ids; passing any one of them is enough. More, or none, is a 400 naming `via`.
  final List<String> stopLocationIds;

  const PlanPassThroughViaLocationInput({
    required this.stopLocationIds,
  });

  factory PlanPassThroughViaLocationInput.fromJson(Map<String, dynamic> json) =>
      PlanPassThroughViaLocationInput(
        stopLocationIds: (json['stopLocationIds'] as List<dynamic>)
            .map((e) => e as String)
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'stopLocationIds': stopLocationIds.map((e) => e).toList(),
      };
}

/// Which modes the search may use.
class PlanModesInput {
  /// Only a direct walk, without transit.
  final bool? directOnly;

  /// Never a journey without a transit leg.
  final bool? transitOnly;
  final PlanTransitModesInput? transit;

  const PlanModesInput({
    this.directOnly,
    this.transitOnly,
    this.transit,
  });

  factory PlanModesInput.fromJson(Map<String, dynamic> json) => PlanModesInput(
        directOnly: json['directOnly'] as bool?,
        transitOnly: json['transitOnly'] as bool?,
        transit: json['transit'] == null
            ? null
            : PlanTransitModesInput.fromJson(
                json['transit'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (directOnly != null) 'directOnly': directOnly!,
        if (transitOnly != null) 'transitOnly': transitOnly!,
        if (transit != null) 'transit': transit!.toJson(),
      };
}

/// Transit modes the search may use.
class PlanTransitModesInput {
  /// The modes an itinerary may ride, each with an optional reluctance. Absent means every mode.
  final List<PlanTransitModePreferenceInput>? transit;

  const PlanTransitModesInput({
    this.transit,
  });

  factory PlanTransitModesInput.fromJson(Map<String, dynamic> json) =>
      PlanTransitModesInput(
        transit: (json['transit'] as List<dynamic>?)
            ?.map((e) => PlanTransitModePreferenceInput.fromJson(
                e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (transit != null)
          'transit': transit!.map((e) => e.toJson()).toList(),
      };
}

/// A transit mode the search may use.
class PlanTransitModePreferenceInput {
  final TransitMode mode;
  final TransitModePreferenceCostInput? cost;

  const PlanTransitModePreferenceInput({
    required this.mode,
    this.cost,
  });

  factory PlanTransitModePreferenceInput.fromJson(Map<String, dynamic> json) =>
      PlanTransitModePreferenceInput(
        mode: TransitMode.fromWire(json['mode'] as String),
        cost: json['cost'] == null
            ? null
            : TransitModePreferenceCostInput.fromJson(
                json['cost'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'mode': mode.toJson(),
        if (cost != null) 'cost': cost!.toJson(),
      };
}

/// Cost settings for a transit mode.
class TransitModePreferenceCostInput {
  /// Multiplier on the time spent riding this mode, from 0.1 to 100000: above 1 avoids the mode, below 1 favours it; rejected, never clamped.
  final double reluctance;

  const TransitModePreferenceCostInput({
    required this.reluctance,
  });

  factory TransitModePreferenceCostInput.fromJson(Map<String, dynamic> json) =>
      TransitModePreferenceCostInput(
        reluctance: (json['reluctance'] as num).toDouble(),
      );

  Map<String, dynamic> toJson() => {
        'reluctance': reluctance,
      };
}

/// Routing preferences. An absent member keeps the environment's default.
class PlanPreferencesInput {
  final PlanStreetPreferencesInput? street;
  final TransitPreferencesInput? transit;
  final AccessibilityPreferencesInput? accessibility;

  const PlanPreferencesInput({
    this.street,
    this.transit,
    this.accessibility,
  });

  factory PlanPreferencesInput.fromJson(Map<String, dynamic> json) =>
      PlanPreferencesInput(
        street: json['street'] == null
            ? null
            : PlanStreetPreferencesInput.fromJson(
                json['street'] as Map<String, dynamic>),
        transit: json['transit'] == null
            ? null
            : TransitPreferencesInput.fromJson(
                json['transit'] as Map<String, dynamic>),
        accessibility: json['accessibility'] == null
            ? null
            : AccessibilityPreferencesInput.fromJson(
                json['accessibility'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (street != null) 'street': street!.toJson(),
        if (transit != null) 'transit': transit!.toJson(),
        if (accessibility != null) 'accessibility': accessibility!.toJson(),
      };
}

/// Street preferences, for walking to, from and between stops.
class PlanStreetPreferencesInput {
  final WalkPreferencesInput? walk;

  const PlanStreetPreferencesInput({
    this.walk,
  });

  factory PlanStreetPreferencesInput.fromJson(Map<String, dynamic> json) =>
      PlanStreetPreferencesInput(
        walk: json['walk'] == null
            ? null
            : WalkPreferencesInput.fromJson(
                json['walk'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (walk != null) 'walk': walk!.toJson(),
      };
}

/// Walking preferences.
class WalkPreferencesInput {
  /// Walking speed on flat ground in metres per second, at least 0.1; rejected, never clamped.
  final double? speed;

  /// How much worse walking is than riding for the same time, a multiplier from 0.1 to 100000; rejected, never clamped.
  final double? reluctance;

  /// Generalized cost added for each boarding, an integer from 0 to 1000000; rejected, never clamped.
  final int? boardCost;

  const WalkPreferencesInput({
    this.speed,
    this.reluctance,
    this.boardCost,
  });

  factory WalkPreferencesInput.fromJson(Map<String, dynamic> json) =>
      WalkPreferencesInput(
        speed: (json['speed'] as num?)?.toDouble(),
        reluctance: (json['reluctance'] as num?)?.toDouble(),
        boardCost: (json['boardCost'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        if (speed != null) 'speed': speed!,
        if (reluctance != null) 'reluctance': reluctance!,
        if (boardCost != null) 'boardCost': boardCost!,
      };
}

/// Transit preferences.
class TransitPreferencesInput {
  final TransferPreferencesInput? transfer;
  final BoardPreferencesInput? board;
  final AlightPreferencesInput? alight;

  /// Routes or agencies to leave out of the search.
  final List<TransitFilterInput>? filters;

  const TransitPreferencesInput({
    this.transfer,
    this.board,
    this.alight,
    this.filters,
  });

  factory TransitPreferencesInput.fromJson(Map<String, dynamic> json) =>
      TransitPreferencesInput(
        transfer: json['transfer'] == null
            ? null
            : TransferPreferencesInput.fromJson(
                json['transfer'] as Map<String, dynamic>),
        board: json['board'] == null
            ? null
            : BoardPreferencesInput.fromJson(
                json['board'] as Map<String, dynamic>),
        alight: json['alight'] == null
            ? null
            : AlightPreferencesInput.fromJson(
                json['alight'] as Map<String, dynamic>),
        filters: (json['filters'] as List<dynamic>?)
            ?.map((e) => TransitFilterInput.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (transfer != null) 'transfer': transfer!.toJson(),
        if (board != null) 'board': board!.toJson(),
        if (alight != null) 'alight': alight!.toJson(),
        if (filters != null)
          'filters': filters!.map((e) => e.toJson()).toList(),
      };
}

/// Transfer preferences.
class TransferPreferencesInput {
  /// Generalized cost added for each transfer, an integer from 0 to 1000000; rejected, never clamped.
  final int? cost;

  /// Least time between alighting one vehicle and boarding the next, on top of the walk between stops, as an ISO-8601 duration: `PT0S` to `PT1H`; rejected, never clamped.
  final String? slack;

  /// Most rides an itinerary may take: `N` allows `N - 1` transfers, and `0` allows walking only. From 0 up to the environment's transfer limit plus 1; rejected, never clamped. Absent means the environment's limit.
  final int? maximumTransfers;

  const TransferPreferencesInput({
    this.cost,
    this.slack,
    this.maximumTransfers,
  });

  factory TransferPreferencesInput.fromJson(Map<String, dynamic> json) =>
      TransferPreferencesInput(
        cost: (json['cost'] as num?)?.toInt(),
        slack: json['slack'] as String?,
        maximumTransfers: (json['maximumTransfers'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        if (cost != null) 'cost': cost!,
        if (slack != null) 'slack': slack!,
        if (maximumTransfers != null) 'maximumTransfers': maximumTransfers!,
      };
}

/// Boarding preferences.
class BoardPreferencesInput {
  /// How much worse waiting at a stop is than riding for the same time, a multiplier from 0.1 to 100000; rejected, never clamped.
  final double? waitReluctance;

  /// Least time at the stop before boarding, as an ISO-8601 duration: `PT0S` to `PT1H`; rejected, never clamped.
  final String? slack;

  const BoardPreferencesInput({
    this.waitReluctance,
    this.slack,
  });

  factory BoardPreferencesInput.fromJson(Map<String, dynamic> json) =>
      BoardPreferencesInput(
        waitReluctance: (json['waitReluctance'] as num?)?.toDouble(),
        slack: json['slack'] as String?,
      );

  Map<String, dynamic> toJson() => {
        if (waitReluctance != null) 'waitReluctance': waitReluctance!,
        if (slack != null) 'slack': slack!,
      };
}

/// Alighting preferences.
class AlightPreferencesInput {
  /// Least time needed to alight, as an ISO-8601 duration: `PT0S` to `PT1H`; rejected, never clamped.
  final String? slack;

  const AlightPreferencesInput({
    this.slack,
  });

  factory AlightPreferencesInput.fromJson(Map<String, dynamic> json) =>
      AlightPreferencesInput(
        slack: json['slack'] as String?,
      );

  Map<String, dynamic> toJson() => {
        if (slack != null) 'slack': slack!,
      };
}

/// A filter on the trips the search may ride.
class TransitFilterInput {
  /// Leave out every trip of a route or agency that any of these selectors names.
  final List<TransitFilterSelectInput>? exclude;

  const TransitFilterInput({
    this.exclude,
  });

  factory TransitFilterInput.fromJson(Map<String, dynamic> json) =>
      TransitFilterInput(
        exclude: (json['exclude'] as List<dynamic>?)
            ?.map((e) =>
                TransitFilterSelectInput.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (exclude != null)
          'exclude': exclude!.map((e) => e.toJson()).toList(),
      };
}

/// Exactly one of `routes`, `agencies`.
class TransitFilterSelectInput {
  /// Feed-prefixed route ids (`<feedId>:<routeId>`).
  final List<String>? routes;

  /// Feed-prefixed agency ids (`<feedId>:<agencyId>`).
  final List<String>? agencies;

  const TransitFilterSelectInput({
    this.routes,
    this.agencies,
  });

  factory TransitFilterSelectInput.fromJson(Map<String, dynamic> json) =>
      TransitFilterSelectInput(
        routes: (json['routes'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
        agencies: (json['agencies'] as List<dynamic>?)
            ?.map((e) => e as String)
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        if (routes != null) 'routes': routes!.map((e) => e).toList(),
        if (agencies != null) 'agencies': agencies!.map((e) => e).toList(),
      };
}

/// Accessibility preferences.
class AccessibilityPreferencesInput {
  final WheelchairPreferencesInput? wheelchair;

  const AccessibilityPreferencesInput({
    this.wheelchair,
  });

  factory AccessibilityPreferencesInput.fromJson(Map<String, dynamic> json) =>
      AccessibilityPreferencesInput(
        wheelchair: json['wheelchair'] == null
            ? null
            : WheelchairPreferencesInput.fromJson(
                json['wheelchair'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (wheelchair != null) 'wheelchair': wheelchair!.toJson(),
      };
}

/// Wheelchair preferences.
class WheelchairPreferencesInput {
  /// Consider wheelchair accessibility in routing. The feed's accessibility data limits what this guarantees.
  final bool? enabled;

  const WheelchairPreferencesInput({
    this.enabled,
  });

  factory WheelchairPreferencesInput.fromJson(Map<String, dynamic> json) =>
      WheelchairPreferencesInput(
        enabled: json['enabled'] as bool?,
      );

  Map<String, dynamic> toJson() => {
        if (enabled != null) 'enabled': enabled!,
      };
}

enum TransitMode {
  airplane('AIRPLANE'),
  bus('BUS'),
  cableCar('CABLE_CAR'),
  carpool('CARPOOL'),
  coach('COACH'),
  ferry('FERRY'),
  funicular('FUNICULAR'),
  gondola('GONDOLA'),
  monorail('MONORAIL'),
  rail('RAIL'),
  snowAndIce('SNOW_AND_ICE'),
  subway('SUBWAY'),
  taxi('TAXI'),
  tram('TRAM'),
  trolleybus('TROLLEYBUS'),
  unknown('UNKNOWN');

  const TransitMode(this.wire);

  final String wire;

  static TransitMode fromWire(String? value) {
    for (final e in TransitMode.values) {
      if (e.wire == value) return e;
    }
    return TransitMode.unknown;
  }

  String toJson() => wire;
}

/// Planning level: `STANDARD` plans arrivals with the p50 delay, `SAFE` p70, `VERY_SAFE` p90; omitted plans on the timetable. Each leg's arrival is planned with that trip's typical delay at the stop on the service date's day type, from the environment's realtime history. Boarding keeps the scheduled departure, and a trip with live realtime uses its realtime times.
enum Reliability {
  standard('STANDARD'),
  safe('SAFE'),
  verySafe('VERY_SAFE'),
  unknown('UNKNOWN');

  const Reliability(this.wire);

  final String wire;

  static Reliability fromWire(String? value) {
    for (final e in Reliability.values) {
      if (e.wire == value) return e;
    }
    return Reliability.unknown;
  }

  String toJson() => wire;
}

/// One page of itineraries. An empty `itineraries` with empty `routingErrors` means the search ran and found nothing in the window: page on with `after` or widen `searchWindow`. A plan the router declines has no itineraries and the reason in `routingErrors`.
class PlanTripResponse {
  final List<Itinerary> itineraries;
  final PlanPageInfo pageInfo;

  /// Why the plan was declined; empty when it was not.
  final List<RoutingError> routingErrors;

  /// The date-time the search started from.
  final String? searchDateTime;

  const PlanTripResponse({
    required this.itineraries,
    required this.pageInfo,
    required this.routingErrors,
    this.searchDateTime,
  });

  factory PlanTripResponse.fromJson(Map<String, dynamic> json) =>
      PlanTripResponse(
        itineraries: (json['itineraries'] as List<dynamic>)
            .map((e) => Itinerary.fromJson(e as Map<String, dynamic>))
            .toList(),
        pageInfo:
            PlanPageInfo.fromJson(json['pageInfo'] as Map<String, dynamic>),
        routingErrors: (json['routingErrors'] as List<dynamic>)
            .map((e) => RoutingError.fromJson(e as Map<String, dynamic>))
            .toList(),
        searchDateTime: json['searchDateTime'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'itineraries': itineraries.map((e) => e.toJson()).toList(),
        'pageInfo': pageInfo.toJson(),
        'routingErrors': routingErrors.map((e) => e.toJson()).toList(),
        if (searchDateTime != null) 'searchDateTime': searchDateTime!,
      };
}

/// One journey, leg by leg. Times are in the feed's time zone.
class Itinerary {
  /// Changes between vehicles. Staying on board as the vehicle carries on as another trip (`interlineWithPreviousLeg`) is not counted.
  final int numberOfTransfers;
  final List<Leg> legs;
  final String? start;
  final String? end;

  /// Seconds from `start` to `end`.
  final int? duration;

  /// Seconds spent waiting at stops.
  final int? waitingTime;

  const Itinerary({
    required this.numberOfTransfers,
    required this.legs,
    this.start,
    this.end,
    this.duration,
    this.waitingTime,
  });

  factory Itinerary.fromJson(Map<String, dynamic> json) => Itinerary(
        numberOfTransfers: (json['numberOfTransfers'] as num).toInt(),
        legs: (json['legs'] as List<dynamic>)
            .map((e) => Leg.fromJson(e as Map<String, dynamic>))
            .toList(),
        start: json['start'] as String?,
        end: json['end'] as String?,
        duration: (json['duration'] as num?)?.toInt(),
        waitingTime: (json['waitingTime'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        'numberOfTransfers': numberOfTransfers,
        'legs': legs.map((e) => e.toJson()).toList(),
        if (start != null) 'start': start!,
        if (end != null) 'end': end!,
        if (duration != null) 'duration': duration!,
        if (waitingTime != null) 'waitingTime': waitingTime!,
      };
}

/// One walk or ride.
class Leg {
  final LegTime start;
  final LegTime end;
  final Place from;
  final Place to;
  final Mode? mode;

  /// Seconds of delay applied to this leg's arrival at the requested `reliability`: that trip's typical delay at the stop on the service date's day type, from the environment's realtime history. Null when `reliability` is omitted or there is no history.
  final int? typicalArrivalDelay;
  final RealtimeState? realtimeState;

  /// True when the leg's times include realtime.
  final bool? realTime;

  /// The GTFS service date of the leg's trip, `YYYY-MM-DD`; null on a walk leg.
  final String? serviceDate;

  /// Null on a walk leg.
  final Route? route;
  final String? headsign;

  /// Metres.
  final double? distance;

  /// Seconds.
  final double? duration;

  /// Null on a walk leg.
  final Trip? trip;

  /// True on a transit leg ridden in the same vehicle as the previous leg: the vehicle carries on as another trip, often under another line number, and the rider stays on board. That change is not counted in `numberOfTransfers`. False on every other leg.
  final bool? interlineWithPreviousLeg;
  final Geometry? legGeometry;

  const Leg({
    required this.start,
    required this.end,
    required this.from,
    required this.to,
    this.mode,
    this.typicalArrivalDelay,
    this.realtimeState,
    this.realTime,
    this.serviceDate,
    this.route,
    this.headsign,
    this.distance,
    this.duration,
    this.trip,
    this.interlineWithPreviousLeg,
    this.legGeometry,
  });

  factory Leg.fromJson(Map<String, dynamic> json) => Leg(
        start: LegTime.fromJson(json['start'] as Map<String, dynamic>),
        end: LegTime.fromJson(json['end'] as Map<String, dynamic>),
        from: Place.fromJson(json['from'] as Map<String, dynamic>),
        to: Place.fromJson(json['to'] as Map<String, dynamic>),
        mode:
            json['mode'] == null ? null : Mode.fromWire(json['mode'] as String),
        typicalArrivalDelay: (json['typicalArrivalDelay'] as num?)?.toInt(),
        realtimeState: json['realtimeState'] == null
            ? null
            : RealtimeState.fromWire(json['realtimeState'] as String),
        realTime: json['realTime'] as bool?,
        serviceDate: json['serviceDate'] as String?,
        route: json['route'] == null
            ? null
            : Route.fromJson(json['route'] as Map<String, dynamic>),
        headsign: json['headsign'] as String?,
        distance: (json['distance'] as num?)?.toDouble(),
        duration: (json['duration'] as num?)?.toDouble(),
        trip: json['trip'] == null
            ? null
            : Trip.fromJson(json['trip'] as Map<String, dynamic>),
        interlineWithPreviousLeg: json['interlineWithPreviousLeg'] as bool?,
        legGeometry: json['legGeometry'] == null
            ? null
            : Geometry.fromJson(json['legGeometry'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'start': start.toJson(),
        'end': end.toJson(),
        'from': from.toJson(),
        'to': to.toJson(),
        if (mode != null) 'mode': mode!.toJson(),
        if (typicalArrivalDelay != null)
          'typicalArrivalDelay': typicalArrivalDelay!,
        if (realtimeState != null) 'realtimeState': realtimeState!.toJson(),
        if (realTime != null) 'realTime': realTime!,
        if (serviceDate != null) 'serviceDate': serviceDate!,
        if (route != null) 'route': route!.toJson(),
        if (headsign != null) 'headsign': headsign!,
        if (distance != null) 'distance': distance!,
        if (duration != null) 'duration': duration!,
        if (trip != null) 'trip': trip!.toJson(),
        if (interlineWithPreviousLeg != null)
          'interlineWithPreviousLeg': interlineWithPreviousLeg!,
        if (legGeometry != null) 'legGeometry': legGeometry!.toJson(),
      };
}

class LegTime {
  final String scheduledTime;

  /// Null without realtime.
  final RealTimeEstimate? estimated;

  const LegTime({
    required this.scheduledTime,
    this.estimated,
  });

  factory LegTime.fromJson(Map<String, dynamic> json) => LegTime(
        scheduledTime: json['scheduledTime'] as String,
        estimated: json['estimated'] == null
            ? null
            : RealTimeEstimate.fromJson(
                json['estimated'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'scheduledTime': scheduledTime,
        if (estimated != null) 'estimated': estimated!.toJson(),
      };
}

class RealTimeEstimate {
  final String time;

  /// The difference from the schedule, as an ISO-8601 duration; negative when early.
  final String delay;

  const RealTimeEstimate({
    required this.time,
    required this.delay,
  });

  factory RealTimeEstimate.fromJson(Map<String, dynamic> json) =>
      RealTimeEstimate(
        time: json['time'] as String,
        delay: json['delay'] as String,
      );

  Map<String, dynamic> toJson() => {
        'time': time,
        'delay': delay,
      };
}

class Place {
  final String? name;

  /// Null when the place is not a stop, as for an origin or destination coordinate.
  final Stop? stop;

  const Place({
    this.name,
    this.stop,
  });

  factory Place.fromJson(Map<String, dynamic> json) => Place(
        name: json['name'] as String?,
        stop: json['stop'] == null
            ? null
            : Stop.fromJson(json['stop'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (name != null) 'name': name!,
        if (stop != null) 'stop': stop!.toJson(),
      };
}

class Stop {
  final String gtfsId;
  final WheelchairBoarding? wheelchairBoarding;

  /// Null when the feed has none.
  final String? platformCode;

  /// Null when the feed has none.
  final String? zoneId;

  const Stop({
    required this.gtfsId,
    this.wheelchairBoarding,
    this.platformCode,
    this.zoneId,
  });

  factory Stop.fromJson(Map<String, dynamic> json) => Stop(
        gtfsId: json['gtfsId'] as String,
        wheelchairBoarding: json['wheelchairBoarding'] == null
            ? null
            : WheelchairBoarding.fromWire(json['wheelchairBoarding'] as String),
        platformCode: json['platformCode'] as String?,
        zoneId: json['zoneId'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        if (wheelchairBoarding != null)
          'wheelchairBoarding': wheelchairBoarding!.toJson(),
        if (platformCode != null) 'platformCode': platformCode!,
        if (zoneId != null) 'zoneId': zoneId!,
      };
}

class Route {
  final String gtfsId;
  final String? shortName;
  final String? longName;

  /// Hex without `#`; null when the feed has none.
  final String? color;

  /// Hex without `#`; null when the feed has none.
  final String? textColor;

  const Route({
    required this.gtfsId,
    this.shortName,
    this.longName,
    this.color,
    this.textColor,
  });

  factory Route.fromJson(Map<String, dynamic> json) => Route(
        gtfsId: json['gtfsId'] as String,
        shortName: json['shortName'] as String?,
        longName: json['longName'] as String?,
        color: json['color'] as String?,
        textColor: json['textColor'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        if (shortName != null) 'shortName': shortName!,
        if (longName != null) 'longName': longName!,
        if (color != null) 'color': color!,
        if (textColor != null) 'textColor': textColor!,
      };
}

class Trip {
  final String gtfsId;
  final BikesAllowed? bikesAllowed;

  const Trip({
    required this.gtfsId,
    this.bikesAllowed,
  });

  factory Trip.fromJson(Map<String, dynamic> json) => Trip(
        gtfsId: json['gtfsId'] as String,
        bikesAllowed: json['bikesAllowed'] == null
            ? null
            : BikesAllowed.fromWire(json['bikesAllowed'] as String),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        if (bikesAllowed != null) 'bikesAllowed': bikesAllowed!.toJson(),
      };
}

class Geometry {
  /// Encoded polyline (precision 1e5).
  final String? points;

  const Geometry({
    this.points,
  });

  factory Geometry.fromJson(Map<String, dynamic> json) => Geometry(
        points: json['points'] as String?,
      );

  Map<String, dynamic> toJson() => {
        if (points != null) 'points': points!,
      };
}

class PlanPageInfo {
  final bool hasNextPage;
  final bool hasPreviousPage;

  /// Send as `before` for the previous page; null when there is none.
  final String? startCursor;

  /// Send as `after` for the next page; null when there is none.
  final String? endCursor;

  /// The window the search covered, as an ISO-8601 duration; null for a declined plan.
  final String? searchWindowUsed;

  const PlanPageInfo({
    required this.hasNextPage,
    required this.hasPreviousPage,
    this.startCursor,
    this.endCursor,
    this.searchWindowUsed,
  });

  factory PlanPageInfo.fromJson(Map<String, dynamic> json) => PlanPageInfo(
        hasNextPage: json['hasNextPage'] as bool,
        hasPreviousPage: json['hasPreviousPage'] as bool,
        startCursor: json['startCursor'] as String?,
        endCursor: json['endCursor'] as String?,
        searchWindowUsed: json['searchWindowUsed'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'hasNextPage': hasNextPage,
        'hasPreviousPage': hasPreviousPage,
        if (startCursor != null) 'startCursor': startCursor!,
        if (endCursor != null) 'endCursor': endCursor!,
        if (searchWindowUsed != null) 'searchWindowUsed': searchWindowUsed!,
      };
}

/// Why the router declined the plan: `LOCATION_NOT_FOUND` for an unknown stop id (`inputField` `FROM`, `TO` or `VIA`), `WALKING_BETTER_THAN_TRANSIT` when the origin and destination are close enough that walking beats transit (`inputField` null), or `OUTSIDE_SERVICE_PERIOD` for a date the feed does not cover (`DATE_TIME`). New codes may be added.
class RoutingError {
  final RoutingErrorCode code;
  final String description;

  /// The request member at fault; null when it is none in particular.
  final InputField? inputField;

  const RoutingError({
    required this.code,
    required this.description,
    this.inputField,
  });

  factory RoutingError.fromJson(Map<String, dynamic> json) => RoutingError(
        code: RoutingErrorCode.fromWire(json['code'] as String),
        description: json['description'] as String,
        inputField: json['inputField'] == null
            ? null
            : InputField.fromWire(json['inputField'] as String),
      );

  Map<String, dynamic> toJson() => {
        'code': code.toJson(),
        'description': description,
        if (inputField != null) 'inputField': inputField!.toJson(),
      };
}

enum RoutingErrorCode {
  locationNotFound('LOCATION_NOT_FOUND'),
  noStopsInRange('NO_STOPS_IN_RANGE'),
  noTransitConnection('NO_TRANSIT_CONNECTION'),
  noTransitConnectionInSearchWindow('NO_TRANSIT_CONNECTION_IN_SEARCH_WINDOW'),
  outsideBounds('OUTSIDE_BOUNDS'),
  outsideServicePeriod('OUTSIDE_SERVICE_PERIOD'),
  walkingBetterThanTransit('WALKING_BETTER_THAN_TRANSIT'),
  unknown('UNKNOWN');

  const RoutingErrorCode(this.wire);

  final String wire;

  static RoutingErrorCode fromWire(String? value) {
    for (final e in RoutingErrorCode.values) {
      if (e.wire == value) return e;
    }
    return RoutingErrorCode.unknown;
  }

  String toJson() => wire;
}

enum InputField {
  dateTime('DATE_TIME'),
  from('FROM'),
  to('TO'),
  via('VIA'),
  unknown('UNKNOWN');

  const InputField(this.wire);

  final String wire;

  static InputField fromWire(String? value) {
    for (final e in InputField.values) {
      if (e.wire == value) return e;
    }
    return InputField.unknown;
  }

  String toJson() => wire;
}

enum Mode {
  airplane('AIRPLANE'),
  bicycle('BICYCLE'),
  bus('BUS'),
  cableCar('CABLE_CAR'),
  car('CAR'),
  carpool('CARPOOL'),
  coach('COACH'),
  ferry('FERRY'),
  flex('FLEX'),
  flexible('FLEXIBLE'),
  funicular('FUNICULAR'),
  gondola('GONDOLA'),
  legSwitch('LEG_SWITCH'),
  monorail('MONORAIL'),
  rail('RAIL'),
  scooter('SCOOTER'),
  subway('SUBWAY'),
  taxi('TAXI'),
  tram('TRAM'),
  transit('TRANSIT'),
  trolleybus('TROLLEYBUS'),
  walk('WALK'),
  unknown('UNKNOWN');

  const Mode(this.wire);

  final String wire;

  static Mode fromWire(String? value) {
    for (final e in Mode.values) {
      if (e.wire == value) return e;
    }
    return Mode.unknown;
  }

  String toJson() => wire;
}

enum RealtimeState {
  added('ADDED'),
  canceled('CANCELED'),
  modified('MODIFIED'),
  scheduled('SCHEDULED'),
  updated('UPDATED'),
  unknown('UNKNOWN');

  const RealtimeState(this.wire);

  final String wire;

  static RealtimeState fromWire(String? value) {
    for (final e in RealtimeState.values) {
      if (e.wire == value) return e;
    }
    return RealtimeState.unknown;
  }

  String toJson() => wire;
}

enum WheelchairBoarding {
  notPossible('NOT_POSSIBLE'),
  noInformation('NO_INFORMATION'),
  possible('POSSIBLE'),
  unknown('UNKNOWN');

  const WheelchairBoarding(this.wire);

  final String wire;

  static WheelchairBoarding fromWire(String? value) {
    for (final e in WheelchairBoarding.values) {
      if (e.wire == value) return e;
    }
    return WheelchairBoarding.unknown;
  }

  String toJson() => wire;
}

enum BikesAllowed {
  allowed('ALLOWED'),
  notAllowed('NOT_ALLOWED'),
  noInformation('NO_INFORMATION'),
  unknown('UNKNOWN');

  const BikesAllowed(this.wire);

  final String wire;

  static BikesAllowed fromWire(String? value) {
    for (final e in BikesAllowed.values) {
      if (e.wire == value) return e;
    }
    return BikesAllowed.unknown;
  }

  String toJson() => wire;
}

/// `stop` is the board, or null for an id that is neither a stop nor a station.
class DeparturesResponse {
  final DepartureBoard? stop;

  const DeparturesResponse({
    this.stop,
  });

  factory DeparturesResponse.fromJson(Map<String, dynamic> json) =>
      DeparturesResponse(
        stop: json['stop'] == null
            ? null
            : DepartureBoard.fromJson(json['stop'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (stop != null) 'stop': stop!.toJson(),
      };
}

/// Departures board for one platform (a stop id) or a whole station (a station id), realtime merged in. A trip's final stop gives no row, since nobody boards there.
class DepartureBoard {
  final String gtfsId;
  final String name;

  /// Null on a station board.
  final WheelchairBoarding? wheelchairBoarding;
  final List<StopDeparturesStoptime>? stoptimesWithoutPatterns;

  const DepartureBoard({
    required this.gtfsId,
    required this.name,
    this.wheelchairBoarding,
    this.stoptimesWithoutPatterns,
  });

  factory DepartureBoard.fromJson(Map<String, dynamic> json) => DepartureBoard(
        gtfsId: json['gtfsId'] as String,
        name: json['name'] as String,
        wheelchairBoarding: json['wheelchairBoarding'] == null
            ? null
            : WheelchairBoarding.fromWire(json['wheelchairBoarding'] as String),
        stoptimesWithoutPatterns:
            (json['stoptimesWithoutPatterns'] as List<dynamic>?)
                ?.map((e) =>
                    StopDeparturesStoptime.fromJson(e as Map<String, dynamic>))
                .toList(),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        'name': name,
        if (wheelchairBoarding != null)
          'wheelchairBoarding': wheelchairBoarding!.toJson(),
        if (stoptimesWithoutPatterns != null)
          'stoptimesWithoutPatterns':
              stoptimesWithoutPatterns!.map((e) => e.toJson()).toList(),
      };
}

class StopDeparturesStoptime {
  /// Unix seconds at the start of the trip's service day; it plus a seconds field gives that time as Unix seconds.
  final int? serviceDay;

  /// Seconds after `serviceDay`.
  final int? scheduledDeparture;

  /// Seconds after `serviceDay`, realtime merged in; the schedule when there is none.
  final int? realtimeDeparture;

  /// True when `realtimeDeparture` comes from realtime.
  final bool? realtime;
  final RealtimeState? realtimeState;

  /// The usual delay at this stop in seconds: the median recorded for that trip on the service date's day type, from the environment's realtime history. Null when there is no history.
  final int? typicalDelay;
  final String? headsign;

  /// The platform or stand the departure leaves from, which tells a station's platforms apart.
  final StopDeparturesStop? stop;
  final StopDeparturesTrip? trip;

  const StopDeparturesStoptime({
    this.serviceDay,
    this.scheduledDeparture,
    this.realtimeDeparture,
    this.realtime,
    this.realtimeState,
    this.typicalDelay,
    this.headsign,
    this.stop,
    this.trip,
  });

  factory StopDeparturesStoptime.fromJson(Map<String, dynamic> json) =>
      StopDeparturesStoptime(
        serviceDay: (json['serviceDay'] as num?)?.toInt(),
        scheduledDeparture: (json['scheduledDeparture'] as num?)?.toInt(),
        realtimeDeparture: (json['realtimeDeparture'] as num?)?.toInt(),
        realtime: json['realtime'] as bool?,
        realtimeState: json['realtimeState'] == null
            ? null
            : RealtimeState.fromWire(json['realtimeState'] as String),
        typicalDelay: (json['typicalDelay'] as num?)?.toInt(),
        headsign: json['headsign'] as String?,
        stop: json['stop'] == null
            ? null
            : StopDeparturesStop.fromJson(json['stop'] as Map<String, dynamic>),
        trip: json['trip'] == null
            ? null
            : StopDeparturesTrip.fromJson(json['trip'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (serviceDay != null) 'serviceDay': serviceDay!,
        if (scheduledDeparture != null)
          'scheduledDeparture': scheduledDeparture!,
        if (realtimeDeparture != null) 'realtimeDeparture': realtimeDeparture!,
        if (realtime != null) 'realtime': realtime!,
        if (realtimeState != null) 'realtimeState': realtimeState!.toJson(),
        if (typicalDelay != null) 'typicalDelay': typicalDelay!,
        if (headsign != null) 'headsign': headsign!,
        if (stop != null) 'stop': stop!.toJson(),
        if (trip != null) 'trip': trip!.toJson(),
      };
}

class StopDeparturesStop {
  final String gtfsId;

  /// Null when the feed has none.
  final String? platformCode;

  const StopDeparturesStop({
    required this.gtfsId,
    this.platformCode,
  });

  factory StopDeparturesStop.fromJson(Map<String, dynamic> json) =>
      StopDeparturesStop(
        gtfsId: json['gtfsId'] as String,
        platformCode: json['platformCode'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        if (platformCode != null) 'platformCode': platformCode!,
      };
}

class StopDeparturesTrip {
  final String gtfsId;
  final StopDeparturesRoute route;
  final BikesAllowed? bikesAllowed;
  final WheelchairBoarding? wheelchairAccessible;

  const StopDeparturesTrip({
    required this.gtfsId,
    required this.route,
    this.bikesAllowed,
    this.wheelchairAccessible,
  });

  factory StopDeparturesTrip.fromJson(Map<String, dynamic> json) =>
      StopDeparturesTrip(
        gtfsId: json['gtfsId'] as String,
        route:
            StopDeparturesRoute.fromJson(json['route'] as Map<String, dynamic>),
        bikesAllowed: json['bikesAllowed'] == null
            ? null
            : BikesAllowed.fromWire(json['bikesAllowed'] as String),
        wheelchairAccessible: json['wheelchairAccessible'] == null
            ? null
            : WheelchairBoarding.fromWire(
                json['wheelchairAccessible'] as String),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        'route': route.toJson(),
        if (bikesAllowed != null) 'bikesAllowed': bikesAllowed!.toJson(),
        if (wheelchairAccessible != null)
          'wheelchairAccessible': wheelchairAccessible!.toJson(),
      };
}

class StopDeparturesRoute {
  final String gtfsId;
  final String? shortName;
  final String? longName;
  final TransitMode? mode;

  /// Hex without `#`; null when the feed has none.
  final String? color;

  /// Hex without `#`; null when the feed has none.
  final String? textColor;

  const StopDeparturesRoute({
    required this.gtfsId,
    this.shortName,
    this.longName,
    this.mode,
    this.color,
    this.textColor,
  });

  factory StopDeparturesRoute.fromJson(Map<String, dynamic> json) =>
      StopDeparturesRoute(
        gtfsId: json['gtfsId'] as String,
        shortName: json['shortName'] as String?,
        longName: json['longName'] as String?,
        mode: json['mode'] == null
            ? null
            : TransitMode.fromWire(json['mode'] as String),
        color: json['color'] as String?,
        textColor: json['textColor'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        if (shortName != null) 'shortName': shortName!,
        if (longName != null) 'longName': longName!,
        if (mode != null) 'mode': mode!.toJson(),
        if (color != null) 'color': color!,
        if (textColor != null) 'textColor': textColor!,
      };
}

/// `trip` is null for an unknown id.
class TripResponse {
  final TripTimetable? trip;

  const TripResponse({
    this.trip,
  });

  factory TripResponse.fromJson(Map<String, dynamic> json) => TripResponse(
        trip: json['trip'] == null
            ? null
            : TripTimetable.fromJson(json['trip'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (trip != null) 'trip': trip!.toJson(),
      };
}

/// One trip on one service date: its stops and times, realtime merged in. On a date without realtime, the rows carry the schedule alone.
class TripTimetable {
  final String gtfsId;
  final TripRoute route;
  final String? directionId;
  final String? tripHeadsign;
  final BikesAllowed? bikesAllowed;
  final WheelchairBoarding? wheelchairAccessible;
  final List<Stoptime>? stoptimesForDate;

  /// The trip's path; null when the feed has no shapes.
  final TripGeometry? tripGeometry;

  const TripTimetable({
    required this.gtfsId,
    required this.route,
    this.directionId,
    this.tripHeadsign,
    this.bikesAllowed,
    this.wheelchairAccessible,
    this.stoptimesForDate,
    this.tripGeometry,
  });

  factory TripTimetable.fromJson(Map<String, dynamic> json) => TripTimetable(
        gtfsId: json['gtfsId'] as String,
        route: TripRoute.fromJson(json['route'] as Map<String, dynamic>),
        directionId: json['directionId'] as String?,
        tripHeadsign: json['tripHeadsign'] as String?,
        bikesAllowed: json['bikesAllowed'] == null
            ? null
            : BikesAllowed.fromWire(json['bikesAllowed'] as String),
        wheelchairAccessible: json['wheelchairAccessible'] == null
            ? null
            : WheelchairBoarding.fromWire(
                json['wheelchairAccessible'] as String),
        stoptimesForDate: (json['stoptimesForDate'] as List<dynamic>?)
            ?.map((e) => Stoptime.fromJson(e as Map<String, dynamic>))
            .toList(),
        tripGeometry: json['tripGeometry'] == null
            ? null
            : TripGeometry.fromJson(
                json['tripGeometry'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        'route': route.toJson(),
        if (directionId != null) 'directionId': directionId!,
        if (tripHeadsign != null) 'tripHeadsign': tripHeadsign!,
        if (bikesAllowed != null) 'bikesAllowed': bikesAllowed!.toJson(),
        if (wheelchairAccessible != null)
          'wheelchairAccessible': wheelchairAccessible!.toJson(),
        if (stoptimesForDate != null)
          'stoptimesForDate': stoptimesForDate!.map((e) => e.toJson()).toList(),
        if (tripGeometry != null) 'tripGeometry': tripGeometry!.toJson(),
      };
}

class TripRoute {
  final String gtfsId;
  final String? shortName;
  final String? longName;
  final TransitMode? mode;

  /// Hex without `#`; null when the feed has none.
  final String? color;

  /// Hex without `#`; null when the feed has none.
  final String? textColor;

  const TripRoute({
    required this.gtfsId,
    this.shortName,
    this.longName,
    this.mode,
    this.color,
    this.textColor,
  });

  factory TripRoute.fromJson(Map<String, dynamic> json) => TripRoute(
        gtfsId: json['gtfsId'] as String,
        shortName: json['shortName'] as String?,
        longName: json['longName'] as String?,
        mode: json['mode'] == null
            ? null
            : TransitMode.fromWire(json['mode'] as String),
        color: json['color'] as String?,
        textColor: json['textColor'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        if (shortName != null) 'shortName': shortName!,
        if (longName != null) 'longName': longName!,
        if (mode != null) 'mode': mode!.toJson(),
        if (color != null) 'color': color!,
        if (textColor != null) 'textColor': textColor!,
      };
}

class TripStop {
  final String gtfsId;
  final String name;
  final double? lat;
  final double? lon;
  final WheelchairBoarding? wheelchairBoarding;

  /// Null when the feed has none.
  final String? platformCode;

  /// Null when the feed has none.
  final String? zoneId;

  const TripStop({
    required this.gtfsId,
    required this.name,
    this.lat,
    this.lon,
    this.wheelchairBoarding,
    this.platformCode,
    this.zoneId,
  });

  factory TripStop.fromJson(Map<String, dynamic> json) => TripStop(
        gtfsId: json['gtfsId'] as String,
        name: json['name'] as String,
        lat: (json['lat'] as num?)?.toDouble(),
        lon: (json['lon'] as num?)?.toDouble(),
        wheelchairBoarding: json['wheelchairBoarding'] == null
            ? null
            : WheelchairBoarding.fromWire(json['wheelchairBoarding'] as String),
        platformCode: json['platformCode'] as String?,
        zoneId: json['zoneId'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'gtfsId': gtfsId,
        'name': name,
        if (lat != null) 'lat': lat!,
        if (lon != null) 'lon': lon!,
        if (wheelchairBoarding != null)
          'wheelchairBoarding': wheelchairBoarding!.toJson(),
        if (platformCode != null) 'platformCode': platformCode!,
        if (zoneId != null) 'zoneId': zoneId!,
      };
}

class Stoptime {
  /// Unix seconds at the start of the trip's service day; it plus a seconds field gives that time as Unix seconds.
  final int? serviceDay;

  /// Seconds after `serviceDay`.
  final int? scheduledArrival;

  /// Seconds after `serviceDay`.
  final int? scheduledDeparture;

  /// Seconds after `serviceDay`, realtime merged in; the schedule when there is none.
  final int? realtimeArrival;

  /// Seconds after `serviceDay`, realtime merged in; the schedule when there is none.
  final int? realtimeDeparture;

  /// True when `realtimeArrival` and `realtimeDeparture` come from realtime.
  final bool? realtime;
  final RealtimeState? realtimeState;

  /// The usual delay at this stop in seconds: the median recorded for that trip on the service date's day type, from the environment's realtime history. Null when there is no history.
  final int? typicalDelay;
  final TripStop? stop;

  const Stoptime({
    this.serviceDay,
    this.scheduledArrival,
    this.scheduledDeparture,
    this.realtimeArrival,
    this.realtimeDeparture,
    this.realtime,
    this.realtimeState,
    this.typicalDelay,
    this.stop,
  });

  factory Stoptime.fromJson(Map<String, dynamic> json) => Stoptime(
        serviceDay: (json['serviceDay'] as num?)?.toInt(),
        scheduledArrival: (json['scheduledArrival'] as num?)?.toInt(),
        scheduledDeparture: (json['scheduledDeparture'] as num?)?.toInt(),
        realtimeArrival: (json['realtimeArrival'] as num?)?.toInt(),
        realtimeDeparture: (json['realtimeDeparture'] as num?)?.toInt(),
        realtime: json['realtime'] as bool?,
        realtimeState: json['realtimeState'] == null
            ? null
            : RealtimeState.fromWire(json['realtimeState'] as String),
        typicalDelay: (json['typicalDelay'] as num?)?.toInt(),
        stop: json['stop'] == null
            ? null
            : TripStop.fromJson(json['stop'] as Map<String, dynamic>),
      );

  Map<String, dynamic> toJson() => {
        if (serviceDay != null) 'serviceDay': serviceDay!,
        if (scheduledArrival != null) 'scheduledArrival': scheduledArrival!,
        if (scheduledDeparture != null)
          'scheduledDeparture': scheduledDeparture!,
        if (realtimeArrival != null) 'realtimeArrival': realtimeArrival!,
        if (realtimeDeparture != null) 'realtimeDeparture': realtimeDeparture!,
        if (realtime != null) 'realtime': realtime!,
        if (realtimeState != null) 'realtimeState': realtimeState!.toJson(),
        if (typicalDelay != null) 'typicalDelay': typicalDelay!,
        if (stop != null) 'stop': stop!.toJson(),
      };
}

class TripGeometry {
  /// Encoded polyline (precision 1e5).
  final String? points;

  /// Number of points.
  final int? length;

  const TripGeometry({
    this.points,
    this.length,
  });

  factory TripGeometry.fromJson(Map<String, dynamic> json) => TripGeometry(
        points: json['points'] as String?,
        length: (json['length'] as num?)?.toInt(),
      );

  Map<String, dynamic> toJson() => {
        if (points != null) 'points': points!,
        if (length != null) 'length': length!,
      };
}

/// Progress, with the itineraries that became final since the previous `chunk`.
class PlanStreamChunkEvent {
  /// Seconds of the window searched so far.
  final int frontier;

  /// Itineraries found so far.
  final int found;

  /// Itineraries sent so far, this chunk's included.
  final int finalized;

  /// Itineraries that became final with this chunk.
  final List<Itinerary> results;

  const PlanStreamChunkEvent({
    required this.frontier,
    required this.found,
    required this.finalized,
    required this.results,
  });

  factory PlanStreamChunkEvent.fromJson(Map<String, dynamic> json) =>
      PlanStreamChunkEvent(
        frontier: (json['frontier'] as num).toInt(),
        found: (json['found'] as num).toInt(),
        finalized: (json['finalized'] as num).toInt(),
        results: (json['results'] as List<dynamic>)
            .map((e) => Itinerary.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'frontier': frontier,
        'found': found,
        'finalized': finalized,
        'results': results.map((e) => e.toJson()).toList(),
      };
}

/// Sent once, after the last `chunk`. To continue, send `endCursor` as `after` or `startCursor` as `before` in a new request.
class PlanStreamPageInfoEvent {
  final bool hasNextPage;
  final bool hasPreviousPage;

  /// Why the plan was declined; empty when it was not.
  final List<RoutingError> routingErrors;

  /// Send as `before` for earlier itineraries; null when there is none.
  final String? startCursor;

  /// Send as `after` for later itineraries; null when there is none.
  final String? endCursor;

  /// The window the stream searched, as an ISO-8601 duration; null for a declined plan.
  final String? searchWindowUsed;

  const PlanStreamPageInfoEvent({
    required this.hasNextPage,
    required this.hasPreviousPage,
    required this.routingErrors,
    this.startCursor,
    this.endCursor,
    this.searchWindowUsed,
  });

  factory PlanStreamPageInfoEvent.fromJson(Map<String, dynamic> json) =>
      PlanStreamPageInfoEvent(
        hasNextPage: json['hasNextPage'] as bool,
        hasPreviousPage: json['hasPreviousPage'] as bool,
        routingErrors: (json['routingErrors'] as List<dynamic>)
            .map((e) => RoutingError.fromJson(e as Map<String, dynamic>))
            .toList(),
        startCursor: json['startCursor'] as String?,
        endCursor: json['endCursor'] as String?,
        searchWindowUsed: json['searchWindowUsed'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'hasNextPage': hasNextPage,
        'hasPreviousPage': hasPreviousPage,
        'routingErrors': routingErrors.map((e) => e.toJson()).toList(),
        if (startCursor != null) 'startCursor': startCursor!,
        if (endCursor != null) 'endCursor': endCursor!,
        if (searchWindowUsed != null) 'searchWindowUsed': searchWindowUsed!,
      };
}

/// The search work this stream used; ends the stream. `stoppedBy` is `targetResults` (enough itineraries sent), `maxWindow` (the whole window searched) or `rejected` (a declined plan); new values may be added.
class PlanStreamDoneEvent {
  /// Search iterations used.
  final int iterations;

  /// Seconds of the window searched.
  final int windowSeconds;

  /// Itineraries sent.
  final int resultCount;

  /// Why the stream stopped.
  final String stoppedBy;

  const PlanStreamDoneEvent({
    required this.iterations,
    required this.windowSeconds,
    required this.resultCount,
    required this.stoppedBy,
  });

  factory PlanStreamDoneEvent.fromJson(Map<String, dynamic> json) =>
      PlanStreamDoneEvent(
        iterations: (json['iterations'] as num).toInt(),
        windowSeconds: (json['windowSeconds'] as num).toInt(),
        resultCount: (json['resultCount'] as num).toInt(),
        stoppedBy: json['stoppedBy'] as String,
      );

  Map<String, dynamic> toJson() => {
        'iterations': iterations,
        'windowSeconds': windowSeconds,
        'resultCount': resultCount,
        'stoppedBy': stoppedBy,
      };
}

/// Error body: a stable machine-readable `code` (a state name) and a human-readable `message`.
class ErrorResponse {
  /// For bad_request: `<field> is required|invalid|out of range|not allowed`.
  final String message;
  final String? code;

  /// The request member a 400 names, as a dot path from the body root (array positions omitted).
  final String? field;

  const ErrorResponse({
    required this.message,
    this.code,
    this.field,
  });

  factory ErrorResponse.fromJson(Map<String, dynamic> json) => ErrorResponse(
        message: json['message'] as String,
        code: json['code'] as String?,
        field: json['field'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'message': message,
        if (code != null) 'code': code!,
        if (field != null) 'field': field!,
      };
}
